using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.ER2Indexer.WCF.BusinessEntities.Generated;
	
namespace Cpchs.ER2Indexer.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: segunda-feira, 10 de Novembro de 2008
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class FileStreamInfo : FileStreamInfo_GEN
	{
        #region Variables

        private object fileInfoPartialStream;

        #endregion

        #region Properties

        public object FileInfoPartialStream
        {
            get { return fileInfoPartialStream; }
            set { fileInfoPartialStream = value; }
        }

        #endregion
		
        /// <summary>
        /// Initialize an new empty FileStreamInfo object.
        /// </summary>
        public FileStreamInfo()
        {
        }
		
		/// <summary>
        /// Initialize an new empty FileStreamInfo object.
        /// </summary>
        public FileStreamInfo(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  FileStreamInfo object with the given parameters.
        /// </summary>
        public  FileStreamInfo(long fileStreamInfoBinId, object fileStreamInfoBinaryData, string fileStreamInfoFileId, string fileStreamInfoFileName, object fileStreamInfoThumbFile) : base(fileStreamInfoBinId, fileStreamInfoBinaryData, fileStreamInfoFileId, fileStreamInfoFileName, fileStreamInfoThumbFile)
        {
        }
		
        public FileStreamInfo(decimal fileStreamInfoXmlId, long fileStreamInfoBinId) : base(fileStreamInfoXmlId, fileStreamInfoBinId)
        {
			
        }
	}
}


