
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Cpchs.Documents.WCF.MessageContracts
{
    /// <summary>
    /// Service Contract Class - UpdateElementDescriptionRequest
    /// </summary>
    [WCF::MessageContract(WrapperName = "UpdateElementDescriptionRequest", WrapperNamespace = "urn:Cpchs.Documents", IsWrapped = true)]
    public partial class UpdateElementDescriptionRequest
    {
        private string companyDb;
        private long elementId;
        private string title;
        private string description;

        [WCF::MessageBodyMember(Namespace = "urn:Cpchs.Documents", Name = "CompanyDb")]
        public string CompanyDb
        {
            get { return companyDb; }
            set { companyDb = value; }
        }

        [WCF::MessageBodyMember(Namespace = "urn:Cpchs.Documents", Name = "ElementId")]
        public long ElementId
        {
            get { return elementId; }
            set { elementId = value; }
        }

        [WCF::MessageBodyMember(Namespace = "urn:Cpchs.Documents", Name = "Title")]
        public string Title
        {
            get { return title; }
            set { title = value; }
        }


        [WCF::MessageBodyMember(Namespace = "urn:Cpchs.Documents", Name = "Description")]
        public string Description
        {
            get { return description; }
            set { description = value; }
        }
    }
}

