using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using System.Runtime.Serialization;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 23 de Dezembro de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class AlertType : AlertType_GEN
	{
        /// <summary>
        /// Initialize an new empty AlertType object.
        /// </summary>
        public AlertType() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty AlertType object.
        /// </summary>
        public AlertType(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  AlertType object with the given parameters.
        /// </summary>
        public  AlertType(string alertTypeCode, string alertTypeAcronym, string alertTypeDesc) : base(alertTypeCode, alertTypeAcronym, alertTypeDesc)
        {
        }
		
        public AlertType(long alertTypeId) : base(alertTypeId)
        {
			
        }
	}
}


