using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: ter?a-feira, 9 de Fevereiro de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class ERConfiguration : ERConfiguration_GEN
	{
        /// <summary>
        /// Initialize an new empty ERConfiguration object.
        /// </summary>
        public ERConfiguration() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty ERConfiguration object.
        /// </summary>
        public ERConfiguration(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  ERConfiguration object with the given parameters.
        /// </summary>
        public  ERConfiguration(long erConfigInstId, long erConfigPlaceId, long erConfigAppId, long erConfigDocTypeId, string erConfigKey, string erConfigValue) : base(erConfigInstId, erConfigPlaceId, erConfigAppId, erConfigDocTypeId, erConfigKey, erConfigValue)
        {
        }
		
        public ERConfiguration(long erConfigInstId, long erConfigPlaceId, long erConfigAppId, long erConfigDocTypeId, string erConfigKey) : base(erConfigInstId, erConfigPlaceId, erConfigAppId, erConfigDocTypeId, erConfigKey)
        {
			
        }
	}
}


