using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 5 de Fevereiro de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class ExecPlace : ExecPlace_GEN
	{
        /// <summary>
        /// Initialize an new empty ExecPlace object.
        /// </summary>
        public ExecPlace() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty ExecPlace object.
        /// </summary>
        public ExecPlace(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  ExecPlace object with the given parameters.
        /// </summary>
        public  ExecPlace(long locexecid, string locexeccode, string locexecacronym, string locexecdescription) : base(locexecid, locexeccode, locexecacronym, locexecdescription)
        {
        }
		
        public ExecPlace(long locexecid) : base(locexecid)
        {
			
        }
	}
}


