using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quinta-feira, 9 de Julho de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Gender : Gender_GEN
	{
		
        /// <summary>
        /// Initialize an new empty Gender object.
        /// </summary>
        public Gender() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Gender object.
        /// </summary>
        public Gender(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  Gender object with the given parameters.
        /// </summary>
        public  Gender(long genId, string genCode, string genAcronym, string genDescription, long genPresOrder) : base(genId, genCode, genAcronym, genDescription, genPresOrder)
        {
        }
		
        public Gender(long genId) : base(genId)
        {
			
        }
	}
}


