using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 16 de Janeiro de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Genre : Genre_GEN
	{
		
        /// <summary>
        /// Initialize an new empty Genre object.
        /// </summary>
        public Genre() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Genre object.
        /// </summary>
        public Genre(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  Genre object with the given parameters.
        /// </summary>
        public Genre(long genreId, string genreCode, string genreAcronym, string genreDescription, long genrePresOrder)
            : base(genreId, genreCode,  genreAcronym, genreDescription, genrePresOrder)
        {
        }
		
        public Genre(long genreId) : base(genreId)
        {
			
        }
	}
}


