using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 17 de Dezembro de 2008
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Institution : Institution_GEN
	{
		
        /// <summary>
        /// Initialize an new empty Institution object.
        /// </summary>
        public Institution() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Institution object.
        /// </summary>
        public Institution(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  Institution object with the given parameters.
        /// </summary>
        public Institution(long institutionId, string institutionCode, string institutionAcronym, string institutionDesc)
            : base(institutionId, institutionCode, institutionAcronym, institutionDesc)
        {
        }
		
        public Institution(long institutionId) : base(institutionId)
        {
			
        }
	}
}


