using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 29 de Julho de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class LocalPatient : LocalPatient_GEN
	{
		
        /// <summary>
        /// Initialize an new empty LocalPatient object.
        /// </summary>
        public LocalPatient() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty LocalPatient object.
        /// </summary>
        public LocalPatient(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
            Cpchs.Eresults.Common.WCF.BusinessEntities.PatientType patientType = new PatientType(reader, companyDB);
            this.LocpatPatientType = patientType;
        }
		
        /// <summary>
        /// Initialize a new  LocalPatient object with the given parameters.
        /// </summary>
        public  LocalPatient(long locpatId, long locpatParentId, long locpatEntityId, long locpatPatientTypeId, string locpatPatientId, string locpatActive) : base(locpatId, locpatParentId, locpatEntityId, locpatPatientTypeId, locpatPatientId, locpatActive)
        {
        }
		
        public LocalPatient(long locpatId) : base(locpatId)
        {
			
        }
	}
}


