using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: segunda-feira, 29 de Dezembro de 2008
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class PatientType : PatientType_GEN
	{
		
        /// <summary>
        /// Initialize an new empty PatientType object.
        /// </summary>
        public PatientType() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty PatientType object.
        /// </summary>
        public PatientType(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  PatientType object with the given parameters.
        /// </summary>
        public PatientType(long patientTypeId, string patientTypeCode, string patientTypeAcronym, string patientTypeDescription, long patientTypeInstitutionId, long patientTypeLocalId)
            : base(patientTypeId, patientTypeCode, patientTypeAcronym, patientTypeDescription, patientTypeInstitutionId, patientTypeLocalId)
        {
        }

        public PatientType(long patientTypeId)
            : base(patientTypeId)
        {

        }
	}
}


