using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: segunda-feira, 6 de Outubro de 2008
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Place : Place_GEN
	{
		
        /// <summary>
        /// Initialize an new empty Place object.
        /// </summary>
        public Place() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Place object.
        /// </summary>
        public Place(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  Place object with the given parameters.
        /// </summary>
        public Place(long placeInstitutionId, long placeId, string placeCode, string placeAcronym, string placeDescription)
            : base(placeInstitutionId, placeId, placeCode, placeAcronym, placeDescription)
        {
        }
		
        public Place(long placeInstitutionId, long placeId) : base(placeInstitutionId, placeId)
        {
			
        }
	}
}


