using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 29 de Maio de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class State : State_GEN
	{
		
        /// <summary>
        /// Initialize an new empty State object.
        /// </summary>
        public State() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty State object.
        /// </summary>
        public State(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  State object with the given parameters.
        /// </summary>
        public State(string stateCode, string stateTag, string stateDescription, string stateScope)
            : base(stateCode, stateTag, stateDescription, stateScope)
        {
        }
		
        public State(long stateId) : base(stateId)
        {
			
        }
	}
}


