using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 5 de Mar?o de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Terapeutic : Terapeutic_GEN
	{
        /// <summary>
        /// Initialize an new empty Terapeutic object.
        /// </summary>
        public Terapeutic() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Terapeutic object.
        /// </summary>
        public Terapeutic(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  Terapeutic object with the given parameters.
        /// </summary>
        public  Terapeutic(long terapeuticId, string terapeuticCode, string terapeuticDescription, string terapeuticAcronym) : base(terapeuticId, terapeuticCode, terapeuticDescription, terapeuticAcronym)
        {
        }
		
        public Terapeutic(long terapeuticId) : base(terapeuticId)
        {
			
        }
	}
}


