//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Cpchs.Documents.WCF.DataContracts
{
	/// <summary>
	/// Data Contract Class - FileInfo
	/// </summary>	
	public partial class FileInfo 
	{
        private long fileElemId;

        [WcfSerialization::DataMember(Name = "FileElemId", IsRequired = false, Order = 99)]
		public long FileElemId
		{
            get { return fileElemId; }
            set { fileElemId = value; }
		}

        private long fileDocumentId;

        [WcfSerialization::DataMember(Name = "FileDocumentId", IsRequired = false, Order = 98)]
        public long FileDocumentId
        {
            get { return fileDocumentId; }
            set { fileDocumentId = value; }
        }

        private string fileThumb;

        [WcfSerialization::DataMember(Name = "FileThumb", IsRequired = false, Order = 100)]
        public string FileThumb
        {
            get { return fileThumb; }
            set { fileThumb = value; }
        }


        private string elementDescription;

        [WcfSerialization::DataMember(Name = "ElementDescription", IsRequired = false, Order = 101)]
        public string ElementDescription
        {
            get { return elementDescription; }
            set { elementDescription = value; }
        }

        private string elementTitle;

        [WcfSerialization::DataMember(Name = "ElementTitle", IsRequired = false, Order = 102)]
        public string ElementTitle
        {
            get { return elementTitle; }
            set { elementTitle = value; }
        }
			
	}
}

