using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Glintths.Er.Common.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Glintths.Er.Common.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 11 de Mar?o de 2011
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract(Name = "WorkspaceDocument", Namespace = "http://glintt.com/types")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class WorkspaceDocument : WorkspaceDocument_GEN
	{
        /// <summary>
        /// Initialize an new empty WorkspaceDocument object.
        /// </summary>
        public WorkspaceDocument() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty WorkspaceDocument object.
        /// </summary>
        public WorkspaceDocument(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
		
        public WorkspaceDocument(long workspaceId, long documentId) : base(workspaceId, documentId)
        {
			
        }
		
		protected void LoadWorkspaceDocument(IDataReader reader, string companyDb)
        {
        }
	}
}


