
using System;

using Glintths.Er.Common.BusinessEntities.Generated;




namespace Glintths.Er.Common.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 11 de Mar?o de 2011
    /// Created By: Generated by CodeSmith
		/// Template Created By: CPCHS psilva, 2005
    /// </summary>
	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public sealed class WorkspaceManagementBER : WorkspaceManagementBER_GEN
    {
		#region Singleton
		private static WorkspaceManagementBER instance = new WorkspaceManagementBER();
		
		public static WorkspaceManagementBER Instance
		{
			get { return instance; }
		}
		#endregion
		private WorkspaceManagementBER()
		{
			
		}

        protected override string GetWorkspaceTreeDBPackageName
        {
            get { return "PCK_ER_WORKSPACES"; }
        }
		
	}
}


