using System;
using System.Data;
using System.Runtime.Serialization;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;

namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 6 de Julho de 2012
    /// Created By: Generated by CodeSmith
    /// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract(Name = "Note", Namespace = "http://glintt.com/types")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Note : Note_GEN
    {
        public string ReqRef { get; set; }

        /// <summary>
        /// Initialize an new empty Note object.
        /// </summary>
        public Note()
            : base()
        {
        }

        /// <summary>
        /// Initialize an new empty Note object.
        /// </summary>
        public Note(IDataReader reader, string companyDB)
            : base(reader, companyDB)
        {
            for (int i = 0; i < reader.FieldCount; i++)
            {
                switch (reader.GetName(i).ToUpper(System.Globalization.CultureInfo.CurrentCulture))
                {
                    case "REQREF":
                        if (!reader.IsDBNull(i)) this.ReqRef = reader.GetString(i);
                        break;
                }
            }
        }

        /// <summary>
        /// Initialize a new  Note object with the given parameters.
        /// </summary>
        public Note(string domId, string domName, string subdomId, string subdomName, string body)
            : base(domId, domName, subdomId, subdomName, body)
        {
        }

        public Note(long id)
            : base(id)
        {
        }

        protected void LoadNote(IDataReader reader, string companyDb)
        {
        }
    }
}