//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glintths.Er.Task.FilesManagementWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileInfoList", Namespace="urn:Cpchs.Documents")]
    [System.SerializableAttribute()]
    public partial class FileInfoList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Glintths.Er.Task.FilesManagementWS.FilesInfo FilesInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Glintths.Er.Task.FilesManagementWS.FilesInfo FilesInfo {
            get {
                return this.FilesInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesInfoField, value) != true)) {
                    this.FilesInfoField = value;
                    this.RaisePropertyChanged("FilesInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FilesInfo", Namespace="urn:Cpchs.Documents", ItemName="FileInfo")]
    [System.SerializableAttribute()]
    public class FilesInfo : System.Collections.Generic.List<Glintths.Er.Task.FilesManagementWS.FileInfo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileInfo", Namespace="urn:Cpchs.Documents")]
    [System.SerializableAttribute()]
    public partial class FileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileBaseUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FileEncryptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileQueryUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileDocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileElemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExtension {
            get {
                return this.FileExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExtensionField, value) != true)) {
                    this.FileExtensionField = value;
                    this.RaisePropertyChanged("FileExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FileBaseUrl {
            get {
                return this.FileBaseUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FileBaseUrlField, value) != true)) {
                    this.FileBaseUrlField = value;
                    this.RaisePropertyChanged("FileBaseUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool FileEncryption {
            get {
                return this.FileEncryptionField;
            }
            set {
                if ((this.FileEncryptionField.Equals(value) != true)) {
                    this.FileEncryptionField = value;
                    this.RaisePropertyChanged("FileEncryption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string FileQueryUrl {
            get {
                return this.FileQueryUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FileQueryUrlField, value) != true)) {
                    this.FileQueryUrlField = value;
                    this.RaisePropertyChanged("FileQueryUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long FileDocumentId {
            get {
                return this.FileDocumentIdField;
            }
            set {
                if ((this.FileDocumentIdField.Equals(value) != true)) {
                    this.FileDocumentIdField = value;
                    this.RaisePropertyChanged("FileDocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long FileElemId {
            get {
                return this.FileElemIdField;
            }
            set {
                if ((this.FileElemIdField.Equals(value) != true)) {
                    this.FileElemIdField = value;
                    this.RaisePropertyChanged("FileElemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string FileThumb {
            get {
                return this.FileThumbField;
            }
            set {
                if ((object.ReferenceEquals(this.FileThumbField, value) != true)) {
                    this.FileThumbField = value;
                    this.RaisePropertyChanged("FileThumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ElementDescription {
            get {
                return this.ElementDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementDescriptionField, value) != true)) {
                    this.ElementDescriptionField = value;
                    this.RaisePropertyChanged("ElementDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ElementTitle {
            get {
                return this.ElementTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementTitleField, value) != true)) {
                    this.ElementTitleField = value;
                    this.RaisePropertyChanged("ElementTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Cpchs.Documents", ConfigurationName="FilesManagementWS.FilesManagementSC")]
    public interface FilesManagementSC {
        
        // CODEGEN: Generating message contract since the wrapper name (GetDocumentFilesRequest) of message GetDocumentFilesRequest does not match the default value (GetDocumentFiles)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Cpchs.Documents.FilesManagementSC.GetDocumentFiles", ReplyAction="urn:Cpchs.Documents.FilesManagementSC.GetDocumentFiles")]
        Glintths.Er.Task.FilesManagementWS.GetDocumentFilesResponse GetDocumentFiles(Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Cpchs.Documents.FilesManagementSC.GetDocumentFiles", ReplyAction="urn:Cpchs.Documents.FilesManagementSC.GetDocumentFiles")]
        System.Threading.Tasks.Task<Glintths.Er.Task.FilesManagementWS.GetDocumentFilesResponse> GetDocumentFilesAsync(Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetFileByElementIdRequest) of message GetFileByElementIdRequest does not match the default value (GetFileByElementId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Cpchs.Documents.FilesManagementSC.GetFileByElementId", ReplyAction="urn:Cpchs.Documents.FilesManagementSC.GetFileByElementId")]
        Glintths.Er.Task.FilesManagementWS.GetFileByElementIdResponse GetFileByElementId(Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Cpchs.Documents.FilesManagementSC.GetFileByElementId", ReplyAction="urn:Cpchs.Documents.FilesManagementSC.GetFileByElementId")]
        System.Threading.Tasks.Task<Glintths.Er.Task.FilesManagementWS.GetFileByElementIdResponse> GetFileByElementIdAsync(Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentFilesRequest", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetDocumentFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public string CompanyDb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=1)]
        public long DocId;
        
        public GetDocumentFilesRequest() {
        }
        
        public GetDocumentFilesRequest(string CompanyDb, long DocId) {
            this.CompanyDb = CompanyDb;
            this.DocId = DocId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentFilesResponse", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetDocumentFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public Glintths.Er.Task.FilesManagementWS.FileInfoList DocumentFiles;
        
        public GetDocumentFilesResponse() {
        }
        
        public GetDocumentFilesResponse(Glintths.Er.Task.FilesManagementWS.FileInfoList DocumentFiles) {
            this.DocumentFiles = DocumentFiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByElementIdRequest", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetFileByElementIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public string CompanyDb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=1)]
        public long ElementId;
        
        public GetFileByElementIdRequest() {
        }
        
        public GetFileByElementIdRequest(string CompanyDb, long ElementId) {
            this.CompanyDb = CompanyDb;
            this.ElementId = ElementId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByElementIdResponse", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetFileByElementIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public Glintths.Er.Task.FilesManagementWS.FileInfo File;
        
        public GetFileByElementIdResponse() {
        }
        
        public GetFileByElementIdResponse(Glintths.Er.Task.FilesManagementWS.FileInfo File) {
            this.File = File;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilesManagementSCChannel : Glintths.Er.Task.FilesManagementWS.FilesManagementSC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilesManagementSCClient : System.ServiceModel.ClientBase<Glintths.Er.Task.FilesManagementWS.FilesManagementSC>, Glintths.Er.Task.FilesManagementWS.FilesManagementSC {
        
        public FilesManagementSCClient() {
        }
        
        public FilesManagementSCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilesManagementSCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesManagementSCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesManagementSCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glintths.Er.Task.FilesManagementWS.GetDocumentFilesResponse Glintths.Er.Task.FilesManagementWS.FilesManagementSC.GetDocumentFiles(Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest request) {
            return base.Channel.GetDocumentFiles(request);
        }
        
        public Glintths.Er.Task.FilesManagementWS.FileInfoList GetDocumentFiles(string CompanyDb, long DocId) {
            Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest inValue = new Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest();
            inValue.CompanyDb = CompanyDb;
            inValue.DocId = DocId;
            Glintths.Er.Task.FilesManagementWS.GetDocumentFilesResponse retVal = ((Glintths.Er.Task.FilesManagementWS.FilesManagementSC)(this)).GetDocumentFiles(inValue);
            return retVal.DocumentFiles;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glintths.Er.Task.FilesManagementWS.GetDocumentFilesResponse> Glintths.Er.Task.FilesManagementWS.FilesManagementSC.GetDocumentFilesAsync(Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest request) {
            return base.Channel.GetDocumentFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glintths.Er.Task.FilesManagementWS.GetDocumentFilesResponse> GetDocumentFilesAsync(string CompanyDb, long DocId) {
            Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest inValue = new Glintths.Er.Task.FilesManagementWS.GetDocumentFilesRequest();
            inValue.CompanyDb = CompanyDb;
            inValue.DocId = DocId;
            return ((Glintths.Er.Task.FilesManagementWS.FilesManagementSC)(this)).GetDocumentFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glintths.Er.Task.FilesManagementWS.GetFileByElementIdResponse Glintths.Er.Task.FilesManagementWS.FilesManagementSC.GetFileByElementId(Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest request) {
            return base.Channel.GetFileByElementId(request);
        }
        
        public Glintths.Er.Task.FilesManagementWS.FileInfo GetFileByElementId(string CompanyDb, long ElementId) {
            Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest inValue = new Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest();
            inValue.CompanyDb = CompanyDb;
            inValue.ElementId = ElementId;
            Glintths.Er.Task.FilesManagementWS.GetFileByElementIdResponse retVal = ((Glintths.Er.Task.FilesManagementWS.FilesManagementSC)(this)).GetFileByElementId(inValue);
            return retVal.File;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glintths.Er.Task.FilesManagementWS.GetFileByElementIdResponse> Glintths.Er.Task.FilesManagementWS.FilesManagementSC.GetFileByElementIdAsync(Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest request) {
            return base.Channel.GetFileByElementIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glintths.Er.Task.FilesManagementWS.GetFileByElementIdResponse> GetFileByElementIdAsync(string CompanyDb, long ElementId) {
            Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest inValue = new Glintths.Er.Task.FilesManagementWS.GetFileByElementIdRequest();
            inValue.CompanyDb = CompanyDb;
            inValue.ElementId = ElementId;
            return ((Glintths.Er.Task.FilesManagementWS.FilesManagementSC)(this)).GetFileByElementIdAsync(inValue);
        }
    }
}
