using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;

namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 26 de Dezembro de 2008
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class DocHierarchy : DocHierarchy_GEN
	{
        public long DocHierarchyInstId { get; set; }
        public long DocHierarchyPlaceId { get; set; }
		
        /// <summary>
        /// Initialize an new empty DocHierarchy object.
        /// </summary>
        public DocHierarchy() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty DocHierarchy object.
        /// </summary>
        public DocHierarchy(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
            for (int i = 0; i < reader.FieldCount; i++)
            {
                switch (reader.GetName(i).ToUpper(System.Globalization.CultureInfo.CurrentCulture))
                {
                    case "DOCHIERARCHYINSTID":
                        if (!reader.IsDBNull(i)) this.DocHierarchyInstId = reader.GetInt64(i);
                        break;
                    case "DOCHIERARCHYPLACEID":
                        if (!reader.IsDBNull(i)) this.DocHierarchyPlaceId = reader.GetInt64(i);
                        break;
                }
            }
        }
		
		
        public DocHierarchy(long docHierarchyDocTypeId, long docHierarchyParentId, long docHierarchyAppId) : base(docHierarchyDocTypeId, docHierarchyParentId, docHierarchyAppId)
        {
			
        }
	}
}


