using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: sexta-feira, 25 de Junho de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Element : Element_GEN
	{
        public string ElemType { get; set; }
        public string ElementUser { get; set; }
        public System.DateTime ElementUpdateDate {get; set;}
        /// <summary>
        /// Initialize an new empty Element object.
        /// </summary>
        public Element() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Element object.
        /// </summary>
        public Element(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
            for (int i = 0; i < reader.FieldCount; i++)
            {
                switch (reader.GetName(i).ToUpper(System.Globalization.CultureInfo.CurrentCulture))
                {
                    case "ELEMENTTYPEDESC":
                        if (!reader.IsDBNull(i)) this.ElemType = reader.GetString(i);
                        break;
                    case "ELEMENTUSER":
                        if (!reader.IsDBNull(i)) this.ElementUser = reader.GetString(i);
                        break;
                    case "ELEMENTUPDATEDATE":
                        if (!reader.IsDBNull(i)) this.ElementUpdateDate = reader.GetDateTime(i);
                        break;
                }
            }
        }
		
        /// <summary>
        /// Initialize a new  Element object with the given parameters.
        /// </summary>
        public  Element(long elementId, long elementVersion, string elementActiveVersion, long elementDocUniqueId, long elementOrder, string elementTitle, string elementDescription, string elementStatus, DateTime? elementDate, string elementExternalId, long elementTypeId, string elementPublic, long elementStatusId, DateTime? elementExecutionDate, DateTime? elementValidationDate, DateTime? elementEmissionDate, string elementReport, long elementReportPresOrder) : base(elementId, elementVersion, elementActiveVersion, elementDocUniqueId, elementOrder, elementTitle, elementDescription, elementStatus, elementDate, elementExternalId, elementTypeId, elementPublic, elementStatusId, elementExecutionDate, elementValidationDate, elementEmissionDate, elementReport, elementReportPresOrder)
        {
        }
		
        public Element(long elementId, long elementVersion) : base(elementId, elementVersion)
        {
			
        }
	}
}


