
using System;
using System.Data;
using System.Collections;

using Cpchs.Eresults.Common.WCF.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
using CPCHS.Common.BusinessEntities;

using Microsoft.Practices.EnterpriseLibrary.Caching;

using Microsoft.Practices.EnterpriseLibrary.Logging;
using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;

namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 29 de Outubro de 2008
    /// Created By: Generated by CodeSmith
		/// Template Created By: CPCHS psilva, 2005
    /// </summary>
	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public sealed class FileManagementBER : FileManagementBER_GEN
    {
		#region Singleton
		private static FileManagementBER instance = new FileManagementBER();
		
		public static FileManagementBER Instance
		{
			get { return instance; }
		}
		#endregion
		private FileManagementBER()
		{
			
		}

        protected override string GetDocumentFilesDBPackageName
        {
            get { return "PCK_DOCUMENTS_FILE"; }
        }

        protected override string GetFileByElementIdDBPackageName
        {
            get { return "PCK_DOCUMENTS_FILE"; }
        }
		
		
		
	}
}


