//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - AdverseReactionInformation
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "AdverseReactionInformation")]
	public partial class AdverseReactionInformation 
	{
		private long unitFractionId;
		private long adverseReactionId;
		private long adverseReactionCode;
		private Glintths.Er.Common.DataContracts.CrudOperation crudOperation;
		private string adverseReactionDescription;
		
		[WcfSerialization::DataMember(Name = "UnitFractionId", IsRequired = false, Order = 0)]
		public long UnitFractionId
		{
		  get { return unitFractionId; }
		  set { unitFractionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AdverseReactionId", IsRequired = false, Order = 1)]
		public long AdverseReactionId
		{
		  get { return adverseReactionId; }
		  set { adverseReactionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AdverseReactionCode", IsRequired = false, Order = 2)]
		public long AdverseReactionCode
		{
		  get { return adverseReactionCode; }
		  set { adverseReactionCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CrudOperation", IsRequired = false, Order = 3)]
		public Glintths.Er.Common.DataContracts.CrudOperation CrudOperation
		{
		  get { return crudOperation; }
		  set { crudOperation = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AdverseReactionDescription", IsRequired = false, Order = 4)]
		public string AdverseReactionDescription
		{
		  get { return adverseReactionDescription; }
		  set { adverseReactionDescription = value; }
		}				
	}
}

