//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - BenefitItem
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "BenefitItem")]
	public partial class BenefitItem 
	{
		private string code;
		private string descricao;
		private System.Nullable<System.DateTime> dataInicio;
		private System.Nullable<System.DateTime> dataFim;
		
		[WcfSerialization::DataMember(Name = "Code", IsRequired = false, Order = 0)]
		public string Code
		{
		  get { return code; }
		  set { code = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Descricao", IsRequired = false, Order = 1)]
		public string Descricao
		{
		  get { return descricao; }
		  set { descricao = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DataInicio", IsRequired = false, Order = 2)]
		public System.Nullable<System.DateTime> DataInicio
		{
		  get { return dataInicio; }
		  set { dataInicio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DataFim", IsRequired = false, Order = 3)]
		public System.Nullable<System.DateTime> DataFim
		{
		  get { return dataFim; }
		  set { dataFim = value; }
		}				
	}
}

