//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - DynamicFormAnswer
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "DynamicFormAnswer")]
	public partial class DynamicFormAnswer 
	{
		private string formXml;
		
		[WcfSerialization::DataMember(Name = "FormXml", IsRequired = false, Order = 0)]
		public string FormXml
		{
		  get { return formXml; }
		  set { formXml = value; }
		}				
	}
}

