//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Efr
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Efr")]
	public partial class Efr 
	{
		private long code;
		private string codeExt;
		private string description;
		private bool mandatoryCardNumber;
		private string country;
		private string id;
		private string extId;
		private string cardNumber;
		
		[WcfSerialization::DataMember(Name = "Code", IsRequired = false, Order = 0)]
		public long Code
		{
		  get { return code; }
		  set { code = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodeExt", IsRequired = false, Order = 1)]
		public string CodeExt
		{
		  get { return codeExt; }
		  set { codeExt = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 2)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MandatoryCardNumber", IsRequired = false, Order = 3)]
		public bool MandatoryCardNumber
		{
		  get { return mandatoryCardNumber; }
		  set { mandatoryCardNumber = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Country", IsRequired = false, Order = 4)]
		public string Country
		{
		  get { return country; }
		  set { country = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 5)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExtId", IsRequired = false, Order = 6)]
		public string ExtId
		{
		  get { return extId; }
		  set { extId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CardNumber", IsRequired = false, Order = 7)]
		public string CardNumber
		{
		  get { return cardNumber; }
		  set { cardNumber = value; }
		}				
	}
}

