//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Entity
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Entity")]
	public partial class Entity 
	{
		private string entityName;
		private string entityId;
		private string entityServices;
		
		[WcfSerialization::DataMember(Name = "EntityName", IsRequired = false, Order = 0)]
		public string EntityName
		{
		  get { return entityName; }
		  set { entityName = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EntityId", IsRequired = false, Order = 1)]
		public string EntityId
		{
		  get { return entityId; }
		  set { entityId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EntityServices", IsRequired = false, Order = 2)]
		public string EntityServices
		{
		  get { return entityServices; }
		  set { entityServices = value; }
		}				
	}
}

