//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - EpisodeContext
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "EpisodeContext")]
	public partial class EpisodeContext 
	{
		private string episodeType;
		private string episodeId;
		
		[WcfSerialization::DataMember(Name = "EpisodeType", IsRequired = true, Order = 0)]
		public string EpisodeType
		{
		  get { return episodeType; }
		  set { episodeType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeId", IsRequired = true, Order = 1)]
		public string EpisodeId
		{
		  get { return episodeId; }
		  set { episodeId = value; }
		}				
	}
}

