//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - ExamPriceList
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "ExamPriceList")]
	public partial class ExamPriceList 
	{
		private string rubr;
		private string code;
		private string codeArs;
		private PriceList prices;
		
		[WcfSerialization::DataMember(Name = "Rubr", IsRequired = false, Order = 0)]
		public string Rubr
		{
		  get { return rubr; }
		  set { rubr = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Code", IsRequired = false, Order = 1)]
		public string Code
		{
		  get { return code; }
		  set { code = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodeArs", IsRequired = false, Order = 2)]
		public string CodeArs
		{
		  get { return codeArs; }
		  set { codeArs = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Prices", IsRequired = false, Order = 3)]
		public PriceList Prices
		{
		  get { return prices; }
		  set { prices = value; }
		}				
	}
}

