//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - ExamPriority
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "ExamPriority")]
	public partial class ExamPriority 
	{
		private long priorityId;
		private string code;
		private string description;
		private string acronym;
		
		[WcfSerialization::DataMember(Name = "PriorityId", IsRequired = false, Order = 0)]
		public long PriorityId
		{
		  get { return priorityId; }
		  set { priorityId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Code", IsRequired = false, Order = 1)]
		public string Code
		{
		  get { return code; }
		  set { code = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 2)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Acronym", IsRequired = false, Order = 3)]
		public string Acronym
		{
		  get { return acronym; }
		  set { acronym = value; }
		}				
	}
}

