//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - ExtraDocumentsSearchFields
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "ExtraDocumentsSearchFields")]
	public partial class ExtraDocumentsSearchFields 
	{
		private ExtraDocumentSearchFieldsList extraDocumentSearchFieldsList;
		
		[WcfSerialization::DataMember(Name = "ExtraDocumentSearchFieldsList", IsRequired = false, Order = 0)]
		public ExtraDocumentSearchFieldsList ExtraDocumentSearchFieldsList
		{
		  get { return extraDocumentSearchFieldsList; }
		  set { extraDocumentSearchFieldsList = value; }
		}				
	}
}

