//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - GenericItems
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "GenericItems")]
	public partial class GenericItems 
	{
		private GenericItemList items;
		private string scope;
		
		[WcfSerialization::DataMember(Name = "Items", IsRequired = false, Order = 0)]
		public GenericItemList Items
		{
		  get { return items; }
		  set { items = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Scope", IsRequired = false, Order = 1)]
		public string Scope
		{
		  get { return scope; }
		  set { scope = value; }
		}				
	}
}

