//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - GroupCollection
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://glintths.er.services.model/2010/glintths")]
	public partial class GroupCollection : System.Collections.Generic.List<Group>
	{
	}
}

