//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - GroupRestrictionsList
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "GroupRestrictionsList")]
	public partial class GroupRestrictionsList 
	{
		private GroupRestrictionCollection groupRestrictions;
		
		[WcfSerialization::DataMember(Name = "GroupRestrictions", IsRequired = false, Order = 0)]
		public GroupRestrictionCollection GroupRestrictions
		{
		  get { return groupRestrictions; }
		  set { groupRestrictions = value; }
		}				
	}
}

