//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - GroupRestriction
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "GroupRestriction")]
	public partial class GroupRestriction 
	{
		private Glintths.Er.Common.DataContracts.Service execService;
		private Glintths.Er.Common.DataContracts.Service reqService;
		private Glintths.Er.Common.DataContracts.HospitalStaff doctor;
		private long groupAssocId;
		private string crudCode;
		
		[WcfSerialization::DataMember(Name = "ExecService", IsRequired = false, Order = 0)]
		public Glintths.Er.Common.DataContracts.Service ExecService
		{
		  get { return execService; }
		  set { execService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqService", IsRequired = false, Order = 1)]
		public Glintths.Er.Common.DataContracts.Service ReqService
		{
		  get { return reqService; }
		  set { reqService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Doctor", IsRequired = false, Order = 2)]
		public Glintths.Er.Common.DataContracts.HospitalStaff Doctor
		{
		  get { return doctor; }
		  set { doctor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "GroupAssocId", IsRequired = false, Order = 4)]
		public long GroupAssocId
		{
		  get { return groupAssocId; }
		  set { groupAssocId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CrudCode", IsRequired = false, Order = 5)]
		public string CrudCode
		{
		  get { return crudCode; }
		  set { crudCode = value; }
		}				
	}
}

