//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - HaemoUnitFraction
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "HaemoUnitFraction")]
	public partial class HaemoUnitFraction 
	{
		private long uniqueId;
		private string component;
		private string fraction;
		private string description;
		private Glintths.Er.Common.DataContracts.Patient patient;
		private Glintths.Er.Common.DataContracts.Service service;
		private string transfusionUser;
		private System.Nullable<System.DateTime> transfusionDate;
		private bool isBypassValidationField;
		private string bypassPurpose;
		private string observations;
		private string notes;
		private AdverseReactionInformationList adverseReactionInformationList;
		private Glintths.Er.Common.DataContracts.ReturnReason returnReason;
		private Glintths.Er.Common.DataContracts.CrudOperation crudOperation;
		private VitalParametersList vitalParametersList;
		private string bloodDescription;
		private string status;
		private bool isAvailableField;
		private bool isAdministeredField;
		private bool isInProgressField;
		private bool isReturnedField;
		private bool hasAdverseReactionsField;
		private Glintths.Er.Common.DataContracts.EpisodeContext episode;
		
		[WcfSerialization::DataMember(Name = "UniqueId", IsRequired = false, Order = 0)]
		public long UniqueId
		{
		  get { return uniqueId; }
		  set { uniqueId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Component", IsRequired = false, Order = 1)]
		public string Component
		{
		  get { return component; }
		  set { component = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Fraction", IsRequired = false, Order = 2)]
		public string Fraction
		{
		  get { return fraction; }
		  set { fraction = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 3)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Patient", IsRequired = false, Order = 4)]
		public Glintths.Er.Common.DataContracts.Patient Patient
		{
		  get { return patient; }
		  set { patient = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Service", IsRequired = false, Order = 5)]
		public Glintths.Er.Common.DataContracts.Service Service
		{
		  get { return service; }
		  set { service = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TransfusionUser", IsRequired = false, Order = 7)]
		public string TransfusionUser
		{
		  get { return transfusionUser; }
		  set { transfusionUser = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TransfusionDate", IsRequired = false, Order = 8)]
		public System.Nullable<System.DateTime> TransfusionDate
		{
		  get { return transfusionDate; }
		  set { transfusionDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "isBypassValidation", IsRequired = false, Order = 10)]
		public bool isBypassValidation
		{
		  get { return isBypassValidationField; }
		  set { isBypassValidationField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BypassPurpose", IsRequired = false, Order = 11)]
		public string BypassPurpose
		{
		  get { return bypassPurpose; }
		  set { bypassPurpose = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Observations", IsRequired = false, Order = 12)]
		public string Observations
		{
		  get { return observations; }
		  set { observations = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Notes", IsRequired = false, Order = 13)]
		public string Notes
		{
		  get { return notes; }
		  set { notes = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AdverseReactionInformationList", IsRequired = false, Order = 14)]
		public AdverseReactionInformationList AdverseReactionInformationList
		{
		  get { return adverseReactionInformationList; }
		  set { adverseReactionInformationList = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReturnReason", IsRequired = false, Order = 15)]
		public Glintths.Er.Common.DataContracts.ReturnReason ReturnReason
		{
		  get { return returnReason; }
		  set { returnReason = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CrudOperation", IsRequired = false, Order = 16)]
		public Glintths.Er.Common.DataContracts.CrudOperation CrudOperation
		{
		  get { return crudOperation; }
		  set { crudOperation = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "VitalParametersList", IsRequired = false, Order = 17)]
		public VitalParametersList VitalParametersList
		{
		  get { return vitalParametersList; }
		  set { vitalParametersList = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BloodDescription", IsRequired = false, Order = 19)]
		public string BloodDescription
		{
		  get { return bloodDescription; }
		  set { bloodDescription = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Status", IsRequired = false, Order = 20)]
		public string Status
		{
		  get { return status; }
		  set { status = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "isAvailable", IsRequired = false, Order = 21)]
		public bool isAvailable
		{
		  get { return isAvailableField; }
		  set { isAvailableField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "isAdministered", IsRequired = false, Order = 22)]
		public bool isAdministered
		{
		  get { return isAdministeredField; }
		  set { isAdministeredField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "isInProgress", IsRequired = false, Order = 23)]
		public bool isInProgress
		{
		  get { return isInProgressField; }
		  set { isInProgressField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "isReturned", IsRequired = false, Order = 24)]
		public bool isReturned
		{
		  get { return isReturnedField; }
		  set { isReturnedField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "hasAdverseReactions", IsRequired = false, Order = 25)]
		public bool hasAdverseReactions
		{
		  get { return hasAdverseReactionsField; }
		  set { hasAdverseReactionsField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Episode", IsRequired = false, Order = 26)]
		public Glintths.Er.Common.DataContracts.EpisodeContext Episode
		{
		  get { return episode; }
		  set { episode = value; }
		}				
	}
}

