//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - HGroups
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "HGroups")]
	public partial class HGroups 
	{
		private HGroupList hGroupList;
		
		[WcfSerialization::DataMember(Name = "HGroupList", IsRequired = false, Order = 0)]
		public HGroupList HGroupList
		{
		  get { return hGroupList; }
		  set { hGroupList = value; }
		}				
	}
}

