//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - HGroupExam
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "HGroupExam")]
	public partial class HGroupExam 
	{
		private long id;
		private string description;
		private string codeRubr;
		private string execServiceCode;
		private string execServiceDescription;
		private string productCode;
		private string productDescription;
		private int quantity;
		private bool isMicro;
		private bool isClinicInfoMandatory;
		private long groupId;
		private string codeExt;
		private string codeArs;
		private bool executeInHospital;
		private string areaArs;
		private string areaArsDesc;
		private bool isQuantityEditable;
		private bool isExamInfoMandatory;
		private bool isCloneable;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public long Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 1)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodeRubr", IsRequired = false, Order = 2)]
		public string CodeRubr
		{
		  get { return codeRubr; }
		  set { codeRubr = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecServiceCode", IsRequired = false, Order = 3)]
		public string ExecServiceCode
		{
		  get { return execServiceCode; }
		  set { execServiceCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecServiceDescription", IsRequired = false, Order = 4)]
		public string ExecServiceDescription
		{
		  get { return execServiceDescription; }
		  set { execServiceDescription = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProductCode", IsRequired = false, Order = 5)]
		public string ProductCode
		{
		  get { return productCode; }
		  set { productCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProductDescription", IsRequired = false, Order = 6)]
		public string ProductDescription
		{
		  get { return productDescription; }
		  set { productDescription = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Quantity", IsRequired = false, Order = 7)]
		public int Quantity
		{
		  get { return quantity; }
		  set { quantity = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsMicro", IsRequired = false, Order = 8)]
		public bool IsMicro
		{
		  get { return isMicro; }
		  set { isMicro = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsClinicInfoMandatory", IsRequired = false, Order = 9)]
		public bool IsClinicInfoMandatory
		{
		  get { return isClinicInfoMandatory; }
		  set { isClinicInfoMandatory = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "GroupId", IsRequired = false, Order = 10)]
		public long GroupId
		{
		  get { return groupId; }
		  set { groupId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodeExt", IsRequired = false, Order = 11)]
		public string CodeExt
		{
		  get { return codeExt; }
		  set { codeExt = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodeArs", IsRequired = false, Order = 12)]
		public string CodeArs
		{
		  get { return codeArs; }
		  set { codeArs = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecuteInHospital", IsRequired = false, Order = 13)]
		public bool ExecuteInHospital
		{
		  get { return executeInHospital; }
		  set { executeInHospital = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AreaArs", IsRequired = false, Order = 14)]
		public string AreaArs
		{
		  get { return areaArs; }
		  set { areaArs = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AreaArsDesc", IsRequired = false, Order = 15)]
		public string AreaArsDesc
		{
		  get { return areaArsDesc; }
		  set { areaArsDesc = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsQuantityEditable", IsRequired = false, Order = 16)]
		public bool IsQuantityEditable
		{
		  get { return isQuantityEditable; }
		  set { isQuantityEditable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsExamInfoMandatory", IsRequired = false, Order = 17)]
		public bool IsExamInfoMandatory
		{
		  get { return isExamInfoMandatory; }
		  set { isExamInfoMandatory = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsCloneable", IsRequired = false, Order = 18)]
		public bool IsCloneable
		{
		  get { return isCloneable; }
		  set { isCloneable = value; }
		}				
	}
}

