//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - HospitalStaff
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "HospitalStaff")]
	public partial class HospitalStaff 
	{
		private string name;
		private string type;
		private string mechanNum;
		private string username;
		private string id;
		private string reqServCode;
		private string reqServDescription;
		private string specialityCode;
		private string specialityDescription;
		
		[WcfSerialization::DataMember(Name = "Name", IsRequired = false, Order = 0)]
		public string Name
		{
		  get { return name; }
		  set { name = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Type", IsRequired = false, Order = 1)]
		public string Type
		{
		  get { return type; }
		  set { type = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MechanNum", IsRequired = false, Order = 2)]
		public string MechanNum
		{
		  get { return mechanNum; }
		  set { mechanNum = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Username", IsRequired = false, Order = 3)]
		public string Username
		{
		  get { return username; }
		  set { username = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 4)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqServCode", IsRequired = false, Order = 5)]
		public string ReqServCode
		{
		  get { return reqServCode; }
		  set { reqServCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqServDescription", IsRequired = false, Order = 6)]
		public string ReqServDescription
		{
		  get { return reqServDescription; }
		  set { reqServDescription = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SpecialityCode", IsRequired = false, Order = 7)]
		public string SpecialityCode
		{
		  get { return specialityCode; }
		  set { specialityCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SpecialityDescription", IsRequired = false, Order = 8)]
		public string SpecialityDescription
		{
		  get { return specialityDescription; }
		  set { specialityDescription = value; }
		}				
	}
}

