//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - ImportHeader
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "ImportHeader")]
	public partial class ImportHeader 
	{
		private Glintths.Er.Common.DataContracts.PatientContext patient;
		private Glintths.Er.Common.DataContracts.EpisodeContext episode;
		
		[WcfSerialization::DataMember(Name = "Patient", IsRequired = false, Order = 0)]
		public Glintths.Er.Common.DataContracts.PatientContext Patient
		{
		  get { return patient; }
		  set { patient = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Episode", IsRequired = false, Order = 1)]
		public Glintths.Er.Common.DataContracts.EpisodeContext Episode
		{
		  get { return episode; }
		  set { episode = value; }
		}				
	}
}

