//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - LabelParameter
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "LabelParameter")]
	public partial class LabelParameter 
	{
		private string key;
		private string val;
		
		[WcfSerialization::DataMember(Name = "Key", IsRequired = false, Order = 0)]
		public string Key
		{
		  get { return key; }
		  set { key = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Val", IsRequired = false, Order = 1)]
		public string Val
		{
		  get { return val; }
		  set { val = value; }
		}				
	}
}

