//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Message
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Message")]
	[WcfSerialization::KnownType(typeof(MessageType))]
	public partial class Message 
	{
		private MessageType msgType;
		private string msg;
		private System.Nullable<bool> canProceed;
		private string notificationMessage;
		private System.Nullable<bool> showNotificationMsg;
		private string action;
		private string actionContext;
		
		[WcfSerialization::DataMember(Name = "MsgType", IsRequired = false, Order = 0)]
		public MessageType MsgType
		{
		  get { return msgType; }
		  set { msgType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Msg", IsRequired = false, Order = 1)]
		public string Msg
		{
		  get { return msg; }
		  set { msg = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CanProceed", IsRequired = false, Order = 2)]
		public System.Nullable<bool> CanProceed
		{
		  get { return canProceed; }
		  set { canProceed = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NotificationMessage", IsRequired = false, Order = 3)]
		public string NotificationMessage
		{
		  get { return notificationMessage; }
		  set { notificationMessage = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ShowNotificationMsg", IsRequired = false, Order = 4)]
		public System.Nullable<bool> ShowNotificationMsg
		{
		  get { return showNotificationMsg; }
		  set { showNotificationMsg = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Action", IsRequired = false, Order = 5)]
		public string Action
		{
		  get { return action; }
		  set { action = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ActionContext", IsRequired = false, Order = 6)]
		public string ActionContext
		{
		  get { return actionContext; }
		  set { actionContext = value; }
		}				
	}
}

