//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Enum - ObservationType
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "ObservationType")]
	public enum ObservationType 
	{
		
		[WcfSerialization::EnumMember(Value="ClinicalInformation")]
		ClinicalInformation = 0,		
		
		[WcfSerialization::EnumMember(Value="ExtraInformation")]
		ExtraInformation = 1,		
		
		[WcfSerialization::EnumMember(Value="RequisitionObservation")]
		RequisitionObservation = 2,		
		
		[WcfSerialization::EnumMember(Value="SampleObservation")]
		SampleObservation = 3,		
		
		[WcfSerialization::EnumMember(Value="ExamObservation")]
		ExamObservation = 4,		
		
		[WcfSerialization::EnumMember(Value="JustificationMotive")]
		JustificationMotive = 5,		
		
		[WcfSerialization::EnumMember(Value="JustificationObservation")]
		JustificationObservation = 6,		
		
		[WcfSerialization::EnumMember(Value="PriorityInfomation")]
		PriorityInfomation = 7,		
		
		[WcfSerialization::EnumMember(Value="DomicileInformation")]
		DomicileInformation = 8,		
	}
}

