//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Observation
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Observation")]
	[WcfSerialization::KnownType(typeof(ObservationType))]
	public partial class Observation 
	{
		private ObservationType type;
		private string body;
		
		[WcfSerialization::DataMember(Name = "Type", IsRequired = true, Order = 0)]
		public ObservationType Type
		{
		  get { return type; }
		  set { type = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Body", IsRequired = true, Order = 1)]
		public string Body
		{
		  get { return body; }
		  set { body = value; }
		}				
	}
}

