//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - OperationSuccess
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "OperationSuccess")]
	public partial class OperationSuccess 
	{
		private bool success;
		private string message;
		
		[WcfSerialization::DataMember(Name = "Success", IsRequired = true, Order = 0)]
		public bool Success
		{
		  get { return success; }
		  set { success = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Message", IsRequired = false, Order = 1)]
		public string Message
		{
		  get { return message; }
		  set { message = value; }
		}				
	}
}

