//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Enum - OrderType
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "OrderType")]
	public enum OrderType 
	{
		
		[WcfSerialization::EnumMember(Value="Descendent")]
		Descendent = 0,		
		
		[WcfSerialization::EnumMember(Value="Ascendant")]
		Ascendant = 1,		
	}
}

