//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - PaginationResponse
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "PaginationResponse")]
	public partial class PaginationResponse 
	{
		private long itemsTotalCount;
		private long startIndex;
		
		[WcfSerialization::DataMember(Name = "ItemsTotalCount", IsRequired = false, Order = 0)]
		public long ItemsTotalCount
		{
		  get { return itemsTotalCount; }
		  set { itemsTotalCount = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "StartIndex", IsRequired = false, Order = 1)]
		public long StartIndex
		{
		  get { return startIndex; }
		  set { startIndex = value; }
		}				
	}
}

