//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Patient
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Patient")]
	public partial class Patient 
	{
		private string id;
		private string name;
		private string type;
		private string uniqueId;
		private System.Nullable<System.DateTime> birthDate;
		private string numBenef;
		private string phone1;
		private string phone2;
		private string sNSNum;
		private string address;
		private string postalCode;
		private string postalCodeLocal;
		private string birthCountry;
		private string district;
		private string gender;
		private string village;
		private string rECM;
		private string county;
		private string codResp;
		private System.Nullable<System.DateTime> numBenefValidDate;
		private string docType;
		private string sourceData;
		private string rnuResponseXml;
		private Glintths.Er.Common.DataContracts.Efr efr;
		private Glintths.Er.Common.DataContracts.Efrs efrList;
		private string descResp;
		private string isento;
		private string country;
		private string snsAcronym;
		private bool madeRnuValidation;
		private Benefits benefits;
		private string docNumber;
		private string extraData;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Name", IsRequired = false, Order = 1)]
		public string Name
		{
		  get { return name; }
		  set { name = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Type", IsRequired = false, Order = 2)]
		public string Type
		{
		  get { return type; }
		  set { type = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UniqueId", IsRequired = false, Order = 3)]
		public string UniqueId
		{
		  get { return uniqueId; }
		  set { uniqueId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BirthDate", IsRequired = false, Order = 4)]
		public System.Nullable<System.DateTime> BirthDate
		{
		  get { return birthDate; }
		  set { birthDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NumBenef", IsRequired = false, Order = 5)]
		public string NumBenef
		{
		  get { return numBenef; }
		  set { numBenef = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Phone1", IsRequired = false, Order = 6)]
		public string Phone1
		{
		  get { return phone1; }
		  set { phone1 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Phone2", IsRequired = false, Order = 7)]
		public string Phone2
		{
		  get { return phone2; }
		  set { phone2 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SNSNum", IsRequired = false, Order = 8)]
		public string SNSNum
		{
		  get { return sNSNum; }
		  set { sNSNum = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Address", IsRequired = false, Order = 9)]
		public string Address
		{
		  get { return address; }
		  set { address = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PostalCode", IsRequired = false, Order = 10)]
		public string PostalCode
		{
		  get { return postalCode; }
		  set { postalCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PostalCodeLocal", IsRequired = false, Order = 11)]
		public string PostalCodeLocal
		{
		  get { return postalCodeLocal; }
		  set { postalCodeLocal = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BirthCountry", IsRequired = false, Order = 12)]
		public string BirthCountry
		{
		  get { return birthCountry; }
		  set { birthCountry = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "District", IsRequired = false, Order = 13)]
		public string District
		{
		  get { return district; }
		  set { district = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Gender", IsRequired = false, Order = 14)]
		public string Gender
		{
		  get { return gender; }
		  set { gender = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Village", IsRequired = false, Order = 15)]
		public string Village
		{
		  get { return village; }
		  set { village = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RECM", IsRequired = false, Order = 16)]
		public string RECM
		{
		  get { return rECM; }
		  set { rECM = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "County", IsRequired = false, Order = 17)]
		public string County
		{
		  get { return county; }
		  set { county = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodResp", IsRequired = false, Order = 18)]
		public string CodResp
		{
		  get { return codResp; }
		  set { codResp = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NumBenefValidDate", IsRequired = false, Order = 19)]
		public System.Nullable<System.DateTime> NumBenefValidDate
		{
		  get { return numBenefValidDate; }
		  set { numBenefValidDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DocType", IsRequired = false, Order = 20)]
		public string DocType
		{
		  get { return docType; }
		  set { docType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SourceData", IsRequired = false, Order = 21)]
		public string SourceData
		{
		  get { return sourceData; }
		  set { sourceData = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RnuResponseXml", IsRequired = false, Order = 22)]
		public string RnuResponseXml
		{
		  get { return rnuResponseXml; }
		  set { rnuResponseXml = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Efr", IsRequired = false, Order = 23)]
		public Glintths.Er.Common.DataContracts.Efr Efr
		{
		  get { return efr; }
		  set { efr = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EfrList", IsRequired = false, Order = 24)]
		public Glintths.Er.Common.DataContracts.Efrs EfrList
		{
		  get { return efrList; }
		  set { efrList = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DescResp", IsRequired = false, Order = 25)]
		public string DescResp
		{
		  get { return descResp; }
		  set { descResp = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Isento", IsRequired = false, Order = 26)]
		public string Isento
		{
		  get { return isento; }
		  set { isento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Country", IsRequired = false, Order = 27)]
		public string Country
		{
		  get { return country; }
		  set { country = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SnsAcronym", IsRequired = false, Order = 28)]
		public string SnsAcronym
		{
		  get { return snsAcronym; }
		  set { snsAcronym = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MadeRnuValidation", IsRequired = false, Order = 29)]
		public bool MadeRnuValidation
		{
		  get { return madeRnuValidation; }
		  set { madeRnuValidation = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Benefits", IsRequired = false, Order = 30)]
		public Benefits Benefits
		{
		  get { return benefits; }
		  set { benefits = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DocNumber", IsRequired = false, Order = 31)]
		public string DocNumber
		{
		  get { return docNumber; }
		  set { docNumber = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExtraData", IsRequired = false, Order = 32)]
		public string ExtraData
		{
		  get { return extraData; }
		  set { extraData = value; }
		}				
	}
}

