//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Enum - PatientAction
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "PatientAction")]
	public enum PatientAction 
	{
		
		[WcfSerialization::EnumMember(Value="RegisterPatient")]
		RegisterPatient = 0,		
		
		[WcfSerialization::EnumMember(Value="UpdatePatient")]
		UpdatePatient = 1,		
	}
}

