//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Patients
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Patients")]
	public partial class Patients 
	{
		private PatientList patientList;
		
		[WcfSerialization::DataMember(Name = "PatientList", IsRequired = false, Order = 0)]
		public PatientList PatientList
		{
		  get { return patientList; }
		  set { patientList = value; }
		}				
	}
}

