//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - PatientSearchFields
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "PatientSearchFields")]
	public partial class PatientSearchFields 
	{
		private string patientType;
		private string patientId;
		private string reqService;
		private string reqDoctor;
		private string execService;
		private string requisitionId;
		private System.Nullable<System.DateTime> requisitationDateBegin;
		private System.Nullable<System.DateTime> requisitationDateEnd;
		private string status;
		private string patientName;
		private string patientUniqueId;
		private System.DateTime birthDate;
		private string sNS;
		private string europeanCard;
		
		[WcfSerialization::DataMember(Name = "PatientType", IsRequired = false, Order = 0)]
		public string PatientType
		{
		  get { return patientType; }
		  set { patientType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientId", IsRequired = false, Order = 1)]
		public string PatientId
		{
		  get { return patientId; }
		  set { patientId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqService", IsRequired = false, Order = 2)]
		public string ReqService
		{
		  get { return reqService; }
		  set { reqService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqDoctor", IsRequired = false, Order = 3)]
		public string ReqDoctor
		{
		  get { return reqDoctor; }
		  set { reqDoctor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecService", IsRequired = false, Order = 4)]
		public string ExecService
		{
		  get { return execService; }
		  set { execService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitionId", IsRequired = false, Order = 5)]
		public string RequisitionId
		{
		  get { return requisitionId; }
		  set { requisitionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitationDateBegin", IsRequired = false, Order = 6)]
		public System.Nullable<System.DateTime> RequisitationDateBegin
		{
		  get { return requisitationDateBegin; }
		  set { requisitationDateBegin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitationDateEnd", IsRequired = false, Order = 7)]
		public System.Nullable<System.DateTime> RequisitationDateEnd
		{
		  get { return requisitationDateEnd; }
		  set { requisitationDateEnd = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Status", IsRequired = false, Order = 8)]
		public string Status
		{
		  get { return status; }
		  set { status = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientName", IsRequired = false, Order = 9)]
		public string PatientName
		{
		  get { return patientName; }
		  set { patientName = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientUniqueId", IsRequired = false, Order = 10)]
		public string PatientUniqueId
		{
		  get { return patientUniqueId; }
		  set { patientUniqueId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BirthDate", IsRequired = false, Order = 11)]
		public System.DateTime BirthDate
		{
		  get { return birthDate; }
		  set { birthDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SNS", IsRequired = false, Order = 12)]
		public string SNS
		{
		  get { return sNS; }
		  set { sNS = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EuropeanCard", IsRequired = false, Order = 13)]
		public string EuropeanCard
		{
		  get { return europeanCard; }
		  set { europeanCard = value; }
		}				
	}
}

