//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - PriceList
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths")]
	public partial class PriceList : System.Collections.Generic.List<Price>
	{
	}
}

