//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Price
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Price")]
	public partial class Price 
	{
		private System.Nullable<double> rubricValue;
		private System.Nullable<double> rubricTaxMod;
		private string efr;
		
		[WcfSerialization::DataMember(Name = "RubricValue", IsRequired = false, Order = 0)]
		public System.Nullable<double> RubricValue
		{
		  get { return rubricValue; }
		  set { rubricValue = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RubricTaxMod", IsRequired = false, Order = 1)]
		public System.Nullable<double> RubricTaxMod
		{
		  get { return rubricTaxMod; }
		  set { rubricTaxMod = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Efr", IsRequired = false, Order = 2)]
		public string Efr
		{
		  get { return efr; }
		  set { efr = value; }
		}				
	}
}

