//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - PrintInformation
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "PrintInformation")]
	public partial class PrintInformation 
	{
		private string endpoint;
		private Glintths.Er.Common.DataContracts.PrintPrintingType printingType;
		private Glintths.Er.Common.DataContracts.PrintOutputType outputType;
		private string printerName;
		
		[WcfSerialization::DataMember(Name = "Endpoint", IsRequired = false, Order = 0)]
		public string Endpoint
		{
		  get { return endpoint; }
		  set { endpoint = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PrintingType", IsRequired = false, Order = 1)]
		public Glintths.Er.Common.DataContracts.PrintPrintingType PrintingType
		{
		  get { return printingType; }
		  set { printingType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "OutputType", IsRequired = false, Order = 2)]
		public Glintths.Er.Common.DataContracts.PrintOutputType OutputType
		{
		  get { return outputType; }
		  set { outputType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PrinterName", IsRequired = false, Order = 3)]
		public string PrinterName
		{
		  get { return printerName; }
		  set { printerName = value; }
		}				
	}
}

