//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Requisition
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Requisition")]
	public partial class Requisition 
	{
		private string uniqueId;
		private string id;
		private System.DateTime date;
		private Glintths.Er.Common.DataContracts.Status status;
		private Glintths.Er.Common.DataContracts.Priority priority;
		private Glintths.Er.Common.DataContracts.Service reqService;
		private Glintths.Er.Common.DataContracts.HospitalStaff reqDoctor;
		private Glintths.Er.Common.DataContracts.Service execService;
		private System.Nullable<System.DateTime> desiredDate;
		private System.Nullable<System.DateTime> execDate;
		private Glintths.Er.Common.DataContracts.HealthcareUnit healthcareUnit;
		private Glintths.Er.Common.DataContracts.RequisitionType type;
		private Glintths.Er.Common.DataContracts.Observations observations;
		private Glintths.Er.Common.DataContracts.Status clinicalStatus;
		private System.Nullable<bool> laterExecution;
		private Glintths.Er.Common.DataContracts.ExecutionPlace executionPlace;
		private RequisitionExamList exams;
		private Glintths.Er.Common.DataContracts.Therapeutics therapeutics;
		private string episodeType;
		private string episodeId;
		private bool isEditable;
		private bool isRemovable;
		private bool isPrintable;
		private bool hasResults;
		private bool removed;
		private Glintths.Er.Common.DataContracts.RiskFactors riskFactors;
		private Glintths.Er.Common.DataContracts.Diagnoses diagnoses;
		private string patientId;
		private string patientType;
		private string patientName;
		private bool hasExtraDocuments;
		private string episodeChildId;
		private string episodeChildType;
		private Glintths.Er.Common.DataContracts.RequisitionPlace requisitionPlace;
		private Glintths.Er.Common.DataContracts.DynamicFormAnswer dynFormAnswer;
		private bool selectedForPrint;
		private bool selectedForPreview;
		private string arsCode;
		private string arsDesc;
		private bool domicile;
		private bool urgent;
		private string efrCode;
		private string efrDescription;
		private string efrCardNumber;
		
		[WcfSerialization::DataMember(Name = "UniqueId", IsRequired = false, Order = 0)]
		public string UniqueId
		{
		  get { return uniqueId; }
		  set { uniqueId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 1)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Date", IsRequired = true, Order = 2)]
		public System.DateTime Date
		{
		  get { return date; }
		  set { date = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Status", IsRequired = true, Order = 3)]
		public Glintths.Er.Common.DataContracts.Status Status
		{
		  get { return status; }
		  set { status = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Priority", IsRequired = true, Order = 4)]
		public Glintths.Er.Common.DataContracts.Priority Priority
		{
		  get { return priority; }
		  set { priority = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqService", IsRequired = true, Order = 5)]
		public Glintths.Er.Common.DataContracts.Service ReqService
		{
		  get { return reqService; }
		  set { reqService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqDoctor", IsRequired = true, Order = 6)]
		public Glintths.Er.Common.DataContracts.HospitalStaff ReqDoctor
		{
		  get { return reqDoctor; }
		  set { reqDoctor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecService", IsRequired = true, Order = 7)]
		public Glintths.Er.Common.DataContracts.Service ExecService
		{
		  get { return execService; }
		  set { execService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DesiredDate", IsRequired = false, Order = 8)]
		public System.Nullable<System.DateTime> DesiredDate
		{
		  get { return desiredDate; }
		  set { desiredDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecDate", IsRequired = false, Order = 9)]
		public System.Nullable<System.DateTime> ExecDate
		{
		  get { return execDate; }
		  set { execDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HealthcareUnit", IsRequired = false, Order = 10)]
		public Glintths.Er.Common.DataContracts.HealthcareUnit HealthcareUnit
		{
		  get { return healthcareUnit; }
		  set { healthcareUnit = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Type", IsRequired = true, Order = 11)]
		public Glintths.Er.Common.DataContracts.RequisitionType Type
		{
		  get { return type; }
		  set { type = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Observations", IsRequired = false, Order = 12)]
		public Glintths.Er.Common.DataContracts.Observations Observations
		{
		  get { return observations; }
		  set { observations = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ClinicalStatus", IsRequired = false, Order = 13)]
		public Glintths.Er.Common.DataContracts.Status ClinicalStatus
		{
		  get { return clinicalStatus; }
		  set { clinicalStatus = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "LaterExecution", IsRequired = false, Order = 14)]
		public System.Nullable<bool> LaterExecution
		{
		  get { return laterExecution; }
		  set { laterExecution = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecutionPlace", IsRequired = true, Order = 15)]
		public Glintths.Er.Common.DataContracts.ExecutionPlace ExecutionPlace
		{
		  get { return executionPlace; }
		  set { executionPlace = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Exams", IsRequired = false, Order = 16)]
		public RequisitionExamList Exams
		{
		  get { return exams; }
		  set { exams = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Therapeutics", IsRequired = false, Order = 17)]
		public Glintths.Er.Common.DataContracts.Therapeutics Therapeutics
		{
		  get { return therapeutics; }
		  set { therapeutics = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeType", IsRequired = true, Order = 18)]
		public string EpisodeType
		{
		  get { return episodeType; }
		  set { episodeType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeId", IsRequired = true, Order = 19)]
		public string EpisodeId
		{
		  get { return episodeId; }
		  set { episodeId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsEditable", IsRequired = false, Order = 20)]
		public bool IsEditable
		{
		  get { return isEditable; }
		  set { isEditable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsRemovable", IsRequired = false, Order = 21)]
		public bool IsRemovable
		{
		  get { return isRemovable; }
		  set { isRemovable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsPrintable", IsRequired = false, Order = 22)]
		public bool IsPrintable
		{
		  get { return isPrintable; }
		  set { isPrintable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HasResults", IsRequired = false, Order = 23)]
		public bool HasResults
		{
		  get { return hasResults; }
		  set { hasResults = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Removed", IsRequired = false, Order = 24)]
		public bool Removed
		{
		  get { return removed; }
		  set { removed = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RiskFactors", IsRequired = false, Order = 25)]
		public Glintths.Er.Common.DataContracts.RiskFactors RiskFactors
		{
		  get { return riskFactors; }
		  set { riskFactors = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Diagnoses", IsRequired = false, Order = 26)]
		public Glintths.Er.Common.DataContracts.Diagnoses Diagnoses
		{
		  get { return diagnoses; }
		  set { diagnoses = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientId", IsRequired = false, Order = 27)]
		public string PatientId
		{
		  get { return patientId; }
		  set { patientId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientType", IsRequired = false, Order = 28)]
		public string PatientType
		{
		  get { return patientType; }
		  set { patientType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientName", IsRequired = false, Order = 29)]
		public string PatientName
		{
		  get { return patientName; }
		  set { patientName = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HasExtraDocuments", IsRequired = false, Order = 30)]
		public bool HasExtraDocuments
		{
		  get { return hasExtraDocuments; }
		  set { hasExtraDocuments = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeChildId", IsRequired = false, Order = 31)]
		public string EpisodeChildId
		{
		  get { return episodeChildId; }
		  set { episodeChildId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeChildType", IsRequired = false, Order = 32)]
		public string EpisodeChildType
		{
		  get { return episodeChildType; }
		  set { episodeChildType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitionPlace", IsRequired = false, Order = 33)]
		public Glintths.Er.Common.DataContracts.RequisitionPlace RequisitionPlace
		{
		  get { return requisitionPlace; }
		  set { requisitionPlace = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DynFormAnswer", IsRequired = false, Order = 34)]
		public Glintths.Er.Common.DataContracts.DynamicFormAnswer DynFormAnswer
		{
		  get { return dynFormAnswer; }
		  set { dynFormAnswer = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SelectedForPrint", IsRequired = false, Order = 35)]
		public bool SelectedForPrint
		{
		  get { return selectedForPrint; }
		  set { selectedForPrint = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SelectedForPreview", IsRequired = false, Order = 36)]
		public bool SelectedForPreview
		{
		  get { return selectedForPreview; }
		  set { selectedForPreview = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ArsCode", IsRequired = false, Order = 37)]
		public string ArsCode
		{
		  get { return arsCode; }
		  set { arsCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ArsDesc", IsRequired = false, Order = 38)]
		public string ArsDesc
		{
		  get { return arsDesc; }
		  set { arsDesc = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Domicile", IsRequired = false, Order = 39)]
		public bool Domicile
		{
		  get { return domicile; }
		  set { domicile = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Urgent", IsRequired = false, Order = 40)]
		public bool Urgent
		{
		  get { return urgent; }
		  set { urgent = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EfrCode", IsRequired = false, Order = 41)]
		public string EfrCode
		{
		  get { return efrCode; }
		  set { efrCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EfrDescription", IsRequired = false, Order = 42)]
		public string EfrDescription
		{
		  get { return efrDescription; }
		  set { efrDescription = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EfrCardNumber", IsRequired = false, Order = 43)]
		public string EfrCardNumber
		{
		  get { return efrCardNumber; }
		  set { efrCardNumber = value; }
		}				
	}
}

