//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - RequisitonHeader
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "RequisitonHeader")]
	public partial class RequisitonHeader 
	{
		private Glintths.Er.Common.DataContracts.PatientContext patient;
		private Glintths.Er.Common.DataContracts.EpisodeContext episode;
		private Glintths.Er.Common.DataContracts.Diagnoses diagnoses;
		private Glintths.Er.Common.DataContracts.Therapeutics therapeutics;
		private Glintths.Er.Common.DataContracts.RiskFactors riskFactors;
		private string sessionId;
		
		[WcfSerialization::DataMember(Name = "Patient", IsRequired = false, Order = 0)]
		public Glintths.Er.Common.DataContracts.PatientContext Patient
		{
		  get { return patient; }
		  set { patient = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Episode", IsRequired = false, Order = 1)]
		public Glintths.Er.Common.DataContracts.EpisodeContext Episode
		{
		  get { return episode; }
		  set { episode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Diagnoses", IsRequired = false, Order = 2)]
		public Glintths.Er.Common.DataContracts.Diagnoses Diagnoses
		{
		  get { return diagnoses; }
		  set { diagnoses = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Therapeutics", IsRequired = false, Order = 3)]
		public Glintths.Er.Common.DataContracts.Therapeutics Therapeutics
		{
		  get { return therapeutics; }
		  set { therapeutics = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RiskFactors", IsRequired = false, Order = 4)]
		public Glintths.Er.Common.DataContracts.RiskFactors RiskFactors
		{
		  get { return riskFactors; }
		  set { riskFactors = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SessionId", IsRequired = false, Order = 5)]
		public string SessionId
		{
		  get { return sessionId; }
		  set { sessionId = value; }
		}				
	}
}

