//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Requisitions
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Requisitions")]
	public partial class Requisitions 
	{
		private RequisitionList requisitionList;
		
		[WcfSerialization::DataMember(Name = "RequisitionList", IsRequired = false, Order = 0)]
		public RequisitionList RequisitionList
		{
		  get { return requisitionList; }
		  set { requisitionList = value; }
		}				
	}
}

