//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - RequisitionSearchFields
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "RequisitionSearchFields")]
	public partial class RequisitionSearchFields 
	{
		private string patientType;
		private string patientId;
		private string episodeType;
		private string episodeId;
		private System.Nullable<System.DateTime> episodeDateBegin;
		private System.Nullable<System.DateTime> episodeDateEnd;
		private string reqService;
		private string reqDoctor;
		private string execService;
		private string requisitionId;
		private System.Nullable<System.DateTime> requisitationDateBegin;
		private System.Nullable<System.DateTime> requisitationDateEnd;
		private string status;
		private System.Nullable<bool> hasResults;
		private string examStatus;
		private string userLogin;
		private string hasAuthPermissions;
		private string arsArea;
		
		[WcfSerialization::DataMember(Name = "PatientType", IsRequired = false, Order = 0)]
		public string PatientType
		{
		  get { return patientType; }
		  set { patientType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PatientId", IsRequired = false, Order = 1)]
		public string PatientId
		{
		  get { return patientId; }
		  set { patientId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeType", IsRequired = false, Order = 2)]
		public string EpisodeType
		{
		  get { return episodeType; }
		  set { episodeType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeId", IsRequired = false, Order = 3)]
		public string EpisodeId
		{
		  get { return episodeId; }
		  set { episodeId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeDateBegin", IsRequired = false, Order = 4)]
		public System.Nullable<System.DateTime> EpisodeDateBegin
		{
		  get { return episodeDateBegin; }
		  set { episodeDateBegin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EpisodeDateEnd", IsRequired = false, Order = 5)]
		public System.Nullable<System.DateTime> EpisodeDateEnd
		{
		  get { return episodeDateEnd; }
		  set { episodeDateEnd = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqService", IsRequired = false, Order = 6)]
		public string ReqService
		{
		  get { return reqService; }
		  set { reqService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReqDoctor", IsRequired = false, Order = 7)]
		public string ReqDoctor
		{
		  get { return reqDoctor; }
		  set { reqDoctor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExecService", IsRequired = false, Order = 8)]
		public string ExecService
		{
		  get { return execService; }
		  set { execService = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitionId", IsRequired = false, Order = 9)]
		public string RequisitionId
		{
		  get { return requisitionId; }
		  set { requisitionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitationDateBegin", IsRequired = false, Order = 10)]
		public System.Nullable<System.DateTime> RequisitationDateBegin
		{
		  get { return requisitationDateBegin; }
		  set { requisitationDateBegin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RequisitationDateEnd", IsRequired = false, Order = 11)]
		public System.Nullable<System.DateTime> RequisitationDateEnd
		{
		  get { return requisitationDateEnd; }
		  set { requisitationDateEnd = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Status", IsRequired = false, Order = 12)]
		public string Status
		{
		  get { return status; }
		  set { status = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HasResults", IsRequired = false, Order = 13)]
		public System.Nullable<bool> HasResults
		{
		  get { return hasResults; }
		  set { hasResults = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ExamStatus", IsRequired = false, Order = 14)]
		public string ExamStatus
		{
		  get { return examStatus; }
		  set { examStatus = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UserLogin", IsRequired = false, Order = 15)]
		public string UserLogin
		{
		  get { return userLogin; }
		  set { userLogin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HasAuthPermissions", IsRequired = false, Order = 16)]
		public string HasAuthPermissions
		{
		  get { return hasAuthPermissions; }
		  set { hasAuthPermissions = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ArsArea", IsRequired = false, Order = 17)]
		public string ArsArea
		{
		  get { return arsArea; }
		  set { arsArea = value; }
		}				
	}
}

