//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - SimpleSampleId
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "SimpleSampleId")]
	public partial class SimpleSampleId 
	{
		private long sampleId;
		private long tubeId;
		private string servExecCode;
		private string tubeDescription;
		private string labelCode;
		private int nCopies;
		private LabelParameters labelParameters;
		private string label;
		
		[WcfSerialization::DataMember(Name = "SampleId", IsRequired = false, Order = 0)]
		public long SampleId
		{
		  get { return sampleId; }
		  set { sampleId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TubeId", IsRequired = false, Order = 1)]
		public long TubeId
		{
		  get { return tubeId; }
		  set { tubeId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ServExecCode", IsRequired = false, Order = 2)]
		public string ServExecCode
		{
		  get { return servExecCode; }
		  set { servExecCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TubeDescription", IsRequired = false, Order = 3)]
		public string TubeDescription
		{
		  get { return tubeDescription; }
		  set { tubeDescription = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "LabelCode", IsRequired = false, Order = 4)]
		public string LabelCode
		{
		  get { return labelCode; }
		  set { labelCode = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NCopies", IsRequired = false, Order = 5)]
		public int NCopies
		{
		  get { return nCopies; }
		  set { nCopies = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "LabelParameters", IsRequired = false, Order = 6)]
		public LabelParameters LabelParameters
		{
		  get { return labelParameters; }
		  set { labelParameters = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Label", IsRequired = false, Order = 7)]
		public string Label
		{
		  get { return label; }
		  set { label = value; }
		}				
	}
}

