//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - SimpleReqId
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "SimpleReqId")]
	public partial class SimpleReqId 
	{
		private string requisitionId;
		private string element;
		private string id;
		private string type;
		private bool selectedForPrint;
		private bool selectedForPreview;
		
		[WcfSerialization::DataMember(Name = "RequisitionId", IsRequired = false, Order = 0)]
		public string RequisitionId
		{
		  get { return requisitionId; }
		  set { requisitionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Element", IsRequired = false, Order = 1)]
		public string Element
		{
		  get { return element; }
		  set { element = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 2)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Type", IsRequired = false, Order = 3)]
		public string Type
		{
		  get { return type; }
		  set { type = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SelectedForPrint", IsRequired = false, Order = 4)]
		public bool SelectedForPrint
		{
		  get { return selectedForPrint; }
		  set { selectedForPrint = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SelectedForPreview", IsRequired = false, Order = 5)]
		public bool SelectedForPreview
		{
		  get { return selectedForPreview; }
		  set { selectedForPreview = value; }
		}				
	}
}

