//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Statuses
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Statuses")]
	public partial class Statuses 
	{
		private StatusList statusList;
		
		[WcfSerialization::DataMember(Name = "StatusList", IsRequired = false, Order = 0)]
		public StatusList StatusList
		{
		  get { return statusList; }
		  set { statusList = value; }
		}				
	}
}

