//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Tracking
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "Tracking")]
	public partial class Tracking 
	{
		private string trackingId;
		private string description;
		private string state;
		private string userCri;
		private System.Nullable<System.DateTime> dtCri;
		private string reason;
		
		[WcfSerialization::DataMember(Name = "TrackingId", IsRequired = false, Order = 0)]
		public string TrackingId
		{
		  get { return trackingId; }
		  set { trackingId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 1)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "State", IsRequired = false, Order = 2)]
		public string State
		{
		  get { return state; }
		  set { state = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UserCri", IsRequired = false, Order = 3)]
		public string UserCri
		{
		  get { return userCri; }
		  set { userCri = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DtCri", IsRequired = false, Order = 4)]
		public System.Nullable<System.DateTime> DtCri
		{
		  get { return dtCri; }
		  set { dtCri = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Reason", IsRequired = false, Order = 5)]
		public string Reason
		{
		  get { return reason; }
		  set { reason = value; }
		}				
	}
}

