//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - URLDefinition
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2010/Glintths", Name = "URLDefinition")]
	public partial class URLDefinition 
	{
		private string uRL;
		private string baseURL;
		private bool isToPrint;
		
		[WcfSerialization::DataMember(Name = "URL", IsRequired = true, Order = 0)]
		public string URL
		{
		  get { return uRL; }
		  set { uRL = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BaseURL", IsRequired = true, Order = 1)]
		public string BaseURL
		{
		  get { return baseURL; }
		  set { baseURL = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsToPrint", IsRequired = true, Order = 2)]
		public bool IsToPrint
		{
		  get { return isToPrint; }
		  set { isToPrint = value; }
		}				
	}
}

