//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - WorkspaceMember
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "WorkspaceMember")]
	public partial class WorkspaceMember 
	{
		private string type;
		private string id;
		private WorkspacePermissions permissions;
		
		[WcfSerialization::DataMember(Name = "Type", IsRequired = false, Order = 1)]
		public string Type
		{
		  get { return type; }
		  set { type = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 2)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Permissions", IsRequired = false, Order = 3)]
		public WorkspacePermissions Permissions
		{
		  get { return permissions; }
		  set { permissions = value; }
		}				
	}
}

