//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Enum - WorkspacePermission
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "WorkspacePermission")]
	public enum WorkspacePermission 
	{
		
		[WcfSerialization::EnumMember(Value="View")]
		View = 0,		
		
		[WcfSerialization::EnumMember(Value="Admin")]
		Admin = 1,		
		
		[WcfSerialization::EnumMember(Value="Promote")]
		Promote = 2,		
		
		[WcfSerialization::EnumMember(Value="Delete")]
		Delete = 3,		
	}
}

