//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Glintths.Er.Common.DataContracts
{
	/// <summary>
	/// Data Contract Class - Workspace
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "Workspace")]
	public partial class Workspace 
	{
		private long id;
		private System.Nullable<long> parentWorkspaceId;
		private bool active;
		private string name;
		private string description;
		private WorkspaceMembers members;
		private Workspaces childWorkspaces;
		private bool isLeaf;
		private int level;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 1)]
		public long Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ParentWorkspaceId", IsRequired = false, Order = 2)]
		public System.Nullable<long> ParentWorkspaceId
		{
		  get { return parentWorkspaceId; }
		  set { parentWorkspaceId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Active", IsRequired = false, Order = 3)]
		public bool Active
		{
		  get { return active; }
		  set { active = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Name", IsRequired = false, Order = 4)]
		public string Name
		{
		  get { return name; }
		  set { name = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 5)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Members", IsRequired = false, Order = 6)]
		public WorkspaceMembers Members
		{
		  get { return members; }
		  set { members = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ChildWorkspaces", IsRequired = false, Order = 7)]
		public Workspaces ChildWorkspaces
		{
		  get { return childWorkspaces; }
		  set { childWorkspaces = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsLeaf", IsRequired = false, Order = 8)]
		public bool IsLeaf
		{
		  get { return isLeaf; }
		  set { isLeaf = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Level", IsRequired = false, Order = 9)]
		public int Level
		{
		  get { return level; }
		  set { level = value; }
		}				
	}
}

