//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Glintths.Er.Workspaces.ServiceImplementation
{	
	/// <summary>
	/// Service Class - WorkspacesManagementWs
	/// </summary>
	[WCF::ServiceBehavior(Name = "WorkspacesManagementWs", 
		Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", 
		InstanceContextMode = WCF::InstanceContextMode.PerSession, 
		ConcurrencyMode = WCF::ConcurrencyMode.Single )]
	public abstract class WorkspacesManagementWsBase : Glintths.Er.Workspaces.ServiceContracts.IWorspacesManagementSC
	{
		#region WorspacesManagementSC Members

		public virtual Glintths.Er.Workspaces.MessageContracts.CreateWorkspaceResponse CreateWorkspace(Glintths.Er.Workspaces.MessageContracts.CreateWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.ActivateWorkspaceResponse ActivateWorkspace(Glintths.Er.Workspaces.MessageContracts.ActivateWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.DeactivateWorkspaceResponse DeactivateWorkspace(Glintths.Er.Workspaces.MessageContracts.DeactivateWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.AddMembersToWorkspaceResponse AddMembersToWorkspace(Glintths.Er.Workspaces.MessageContracts.AddMembersToWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.RemoveMembersFromWorkspaceResponse RemoveMembersFromWorkspace(Glintths.Er.Workspaces.MessageContracts.RemoveMembersFromWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.GetWorkspaceResponse GetWorkspace(Glintths.Er.Workspaces.MessageContracts.GetWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.AddChildsToWorkspaceResponse AddChildsToWorkspace(Glintths.Er.Workspaces.MessageContracts.AddChildsToWorkspaceRequest request)
		{
			return null;
		}

		public virtual Glintths.Er.Workspaces.MessageContracts.GetWorkspaceTreeResponse GetWorkspaceTree(Glintths.Er.Workspaces.MessageContracts.GetWorkspaceTreeRequest request)
		{
			return null;
		}

        public virtual Glintths.Er.Workspaces.MessageContracts.RemoveWorkspaceDocumentResponse RemoveWorkspaceDocument(Glintths.Er.Workspaces.MessageContracts.RemoveWorkspaceDocumentResquest request)
        {
            return null;
        }

		#endregion		
		
	}
	
	public partial class WorkspacesManagementWs : WorkspacesManagementWsBase
	{
	}
	
}

