using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: s?bado, 28 de Novembro de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class LinkTypeArg : LinkTypeArg_GEN
	{
		
        /// <summary>
        /// Initialize an new empty LinkTypeArg object.
        /// </summary>
        public LinkTypeArg() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty LinkTypeArg object.
        /// </summary>
        public LinkTypeArg(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  LinkTypeArg object with the given parameters.
        /// </summary>
        public  LinkTypeArg(long linkTypeArgLinkTypeId, long linkTypeArgId, string linkTypeArgArg, string linkTypeArgMask, string linkTypeArgStatic, string linkTypeArgExternal) : base(linkTypeArgLinkTypeId, linkTypeArgId, linkTypeArgArg, linkTypeArgMask, linkTypeArgStatic, linkTypeArgExternal)
        {
        }
		
        public LinkTypeArg(long linkTypeArgLinkTypeId, long linkTypeArgId) : base(linkTypeArgLinkTypeId, linkTypeArgId)
        {
			
        }
	}
}


