
using System;
using System.Data;
using System.Collections;

using Cpchs.Eresults.Common.WCF.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
using CPCHS.Common.BusinessEntities;

using Microsoft.Practices.EnterpriseLibrary.Caching;

using Microsoft.Practices.EnterpriseLibrary.Logging;
using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;

namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 14 de Outubro de 2009
    /// Created By: Generated by CodeSmith
		/// Template Created By: CPCHS psilva, 2005
    /// </summary>
	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public sealed class LinkManagementBER : LinkManagementBER_GEN
    {
		#region Singleton
		private static LinkManagementBER instance = new LinkManagementBER();
		
		public static LinkManagementBER Instance
		{
			get { return instance; }
		}
		#endregion
		private LinkManagementBER()
		{
			
		}

        protected override string GetDocumentLinksDBPackageName
        {
            get { return "PCK_DOCUMENTS_LINK"; }
        }

        protected override string GetDocumentLinksParamsDBPackageName
        {
            get { return "PCK_DOCUMENTS_LINK"; }
        }

        protected override string GetLinkByElementIdDBPackageName
        {
            get { return "PCK_DOCUMENTS_LINK"; }
        }

        protected override string GetLinkByElementIdParamsDBPackageName
        {
            get { return "PCK_DOCUMENTS_LINK"; }
        }
		
	}
}


