using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 14 de Outubro de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class LinkParam : LinkParam_GEN
	{
		
        /// <summary>
        /// Initialize an new empty LinkParam object.
        /// </summary>
        public LinkParam() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty LinkParam object.
        /// </summary>
        public LinkParam(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  LinkParam object with the given parameters.
        /// </summary>
        public  LinkParam(long linkParamElemId, long linkParamVersionCode, long linkParamId, string linkParamArg, string linkParamValue) : base(linkParamElemId, linkParamVersionCode, linkParamId, linkParamArg, linkParamValue)
        {
        }
		
        public LinkParam(long linkParamElemId, long linkParamVersionCode, long linkParamId) : base(linkParamElemId, linkParamVersionCode, linkParamId)
        {
			
        }
	}
}


