using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;

namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: segunda-feira, 6 de Outubro de 2008
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class EpisodeType : EpisodeType_GEN
	{
        public string EpiTypeExt { get; set; }
		
        /// <summary>
        /// Initialize an new empty EpisodeType object.
        /// </summary>
        public EpisodeType() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty EpisodeType object.
        /// </summary>
        public EpisodeType(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
            LoadFromReader(reader);
        }

        private void LoadFromReader(IDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                for (int i = 0; i < reader.FieldCount; i++)
                {
                    switch (reader.GetName(i).ToUpper(System.Globalization.CultureInfo.CurrentCulture))
                    {
                        case "EPITYPEEXT":
                            if (!reader.IsDBNull(i)) this.EpiTypeExt = Convert.ToString(reader.GetValue(i));
                            break;
                    }
                }
            }
        }
		
        /// <summary>
        /// Initialize a new  EpisodeType object with the given parameters.
        /// </summary>
        public  EpisodeType(long epiTypeId, string epiTypeCode, string epiTypeAcronym, string epiTypeDescription) : base(epiTypeId, epiTypeCode, epiTypeAcronym, epiTypeDescription)
        {
        }
		
        public EpisodeType(long epiTypeId) : base(epiTypeId)
        {
			
        }
	}
}


