using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 10 de Novembro de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class ExternalEpisode : ExternalEpisode_GEN
	{
        /// <summary>
        /// Initialize an new empty ExternalEpisode object.
        /// </summary>
        public ExternalEpisode() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty ExternalEpisode object.
        /// </summary>
        public ExternalEpisode(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  ExternalEpisode object with the given parameters.
        /// </summary>
        public  ExternalEpisode(string pattype, string patid, string episodetype, string episodeid, DateTime? episodestartdt, DateTime? episodeenddt) : base(pattype, patid, episodetype, episodeid, episodestartdt, episodeenddt)
        {
        }
		
	}
}


