using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 27 de Outubro de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class VideoProcessorJobState : VideoProcessorJobState_GEN
	{
        /// <summary>
        /// Initialize an new empty VideoProcessorJobState object.
        /// </summary>
        public VideoProcessorJobState() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty VideoProcessorJobState object.
        /// </summary>
        public VideoProcessorJobState(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  VideoProcessorJobState object with the given parameters.
        /// </summary>
        public  VideoProcessorJobState(long jobClient, long jobStatus, DateTime? jobRegisterTimestamp, DateTime? jobCompletedTimestamp, long jobCompletedPercentage, long jobContext, string jobClientFileDeleted, string jobURL, object jobXMLData, object jobErrorLog, string jobData) : base(jobClient, jobStatus, jobRegisterTimestamp, jobCompletedTimestamp, jobCompletedPercentage, jobContext, jobClientFileDeleted, jobURL, jobXMLData, jobErrorLog, jobData)
        {
        }
		
        public VideoProcessorJobState(long jobId) : base(jobId)
        {
			
        }
		
		protected void LoadVideoProcessorJobState(IDataReader reader, string companyDb)
        {
        }
	}
}


