//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Glintths.Er.Interop.DataContracts;
using Cpchs.Eresults.Common.WCF.BusinessEntities;

namespace Glintths.Er.Interop.ServiceImplementation
{
    public static class TranslateBetweenComputerAndVideoProcessorClient
    {
        public static Glintths.Er.Interop.DataContracts.Computer TranslateVideoProcessorClientToComputer(Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorClient from)
        {
            Glintths.Er.Interop.DataContracts.Computer to = new Glintths.Er.Interop.DataContracts.Computer();
            to.ComputerId = from.ComputerId;
            to.ComputerName = from.ComputerName;
            return to;
        }

        public static Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorClient TranslateComputerToVideoProcessorClient(Glintths.Er.Interop.DataContracts.Computer from)
        {
            Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorClient to = new Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorClient();
            to.ComputerId = from.ComputerId;
            to.ComputerName = from.ComputerName;
            return to;
        }
    }
}

