//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Cpchs.Eresults.Common.WCF.BusinessEntities;
using Glintths.Er.Interop.DataContracts;

namespace Glintths.Er.Interop.ServiceImplementation
{
    public static class TranslateBetweenVideoProcessorJobInfoAndJobInfo
    {
        public static Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobInfo TranslateJobInfoToVideoProcessorJobInfo(Glintths.Er.Interop.DataContracts.JobInfo from)
        {
            Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobInfo to = new Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobInfo();
            to.JobId = from.JobID;
            to.JobStatus = Convert.ToInt64(from.JobStatus);
            to.JobRegisterTimestamp = from.JobRegisteredTimestamp;
            to.JobCompletedTimestamp = from.JobCompletedTimestamp;
            to.JobCompletedPercentage = from.JobPercentage;
            to.JobClientFileDeleted = from.JobClientFileDeleted;
            to.JobURL = from.JobURL;
            to.ComputerName = from.JobClient;
            to.ContextName = from.JobContext;
            return to;
        }

        public static Glintths.Er.Interop.DataContracts.JobInfo TranslateVideoProcessorJobInfoToJobInfo(Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobInfo from)
        {
            Glintths.Er.Interop.DataContracts.JobInfo to = new Glintths.Er.Interop.DataContracts.JobInfo();
            to.JobID = from.JobId;
            to.JobStatus = from.JobStatus.ToString();
            to.JobRegisteredTimestamp = Convert.ToDateTime(from.JobRegisterTimestamp);
            to.JobCompletedTimestamp = Convert.ToDateTime(from.JobCompletedTimestamp);
            to.JobPercentage = from.JobCompletedPercentage;
            to.JobClientFileDeleted = from.JobClientFileDeleted;
            to.JobURL = from.JobURL;
            to.JobClient = from.ComputerName;
            to.JobContext = from.ContextName;
            to.jobData = from.JobData;
            return to;
        }
    }
}

