//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Glintths.Er.Interop.ServiceImplementation
{
    public static class TranslateBetweenVideoProcessorJobStateAndJob
    {
        //public static Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobState TranslateJobToVideoProcessorJobState(Glintths.Er.Interop.DataContracts.Job from)
        //{
        //    Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobState to = new Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobState();
        //    to.JobId = from.JobID;
        //    to.JobURL = from.JobURL;
        //    //to.JobXMLData = from.Dados.Documento;
        //    return to;
        //}

        public static Glintths.Er.Interop.DataContracts.Job TranslateVideoProcessorJobStateToJob(Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorJobState from)
        {
            Glintths.Er.Interop.DataContracts.Job to = new Glintths.Er.Interop.DataContracts.Job();
            to.JobID = from.JobId;
            to.JobURL = from.JobURL;
            Cpchs.ER2Indexer.WCF.BusinessEntities.Dados temp = Cpchs.ER2Indexer.WCF.BusinessEntities.Dados.Deserialize((string)from.JobXMLData);
            to.DataPath = temp.Documento.Instituicao + "_" + temp.Documento.Local + "_" + temp.Documento.Origem + "_" + temp.Documento.Tipo + "_" + temp.Documento.Id + "_" + temp.Documento.Elemento[0].IdExternoElem + @"\";
            return to;
        }
    }
}

