//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Cpchs.Eresults.Common.WCF.BusinessEntities;
using Glintths.Er.Interop.DataContracts;

namespace Glintths.Er.Interop.ServiceImplementation
{
    public static class TranslateBetweenVideoProcessorContextAndContext
    {
        public static Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorContext TranslateContextToVideoProcessorContext(Glintths.Er.Interop.DataContracts.Context from)
        {
            Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorContext to = new Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorContext();
            to.ContextId = from.ContextId;
            to.ContextName = from.ContextName;
            return to;
        }

        public static Glintths.Er.Interop.DataContracts.Context TranslateVideoProcessorContextToContext(Cpchs.Eresults.Common.WCF.BusinessEntities.VideoProcessorContext from)
        {
            Glintths.Er.Interop.DataContracts.Context to = new Glintths.Er.Interop.DataContracts.Context();
            to.ContextId = from.ContextId;
            to.ContextName = from.ContextName;
            return to;
        }
    }
}

