
using System;
using System.Data;
using System.Collections;

using Glintths.Er.Common.BusinessEntities;
using Glintths.Er.Common.BusinessEntities.Generated;
	
using CPCHS.Common.BusinessEntities;

using Microsoft.Practices.EnterpriseLibrary.Caching;

using Microsoft.Practices.EnterpriseLibrary.Logging;
using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;

namespace Glintths.Er.Common.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 25 de Agosto de 2010
    /// Created By: Generated by CodeSmith
		/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public sealed class HospitalStaffManagementBER : HospitalStaffManagementBER_GEN
    {
        #region Singleton
        private static HospitalStaffManagementBER instance = new HospitalStaffManagementBER();

        public static HospitalStaffManagementBER Instance
        {
            get { return instance; }
        }
        #endregion
        private HospitalStaffManagementBER()
        {

        }

        protected override string GetAllHospitalStaffDBPackageName
        {
            get { return "PCK_ENTITIES_HOSPITALSTAFF"; }
        }

        protected override string SetHospitalStaffUserDBPackageName
        {
            get { return "PCK_ENTITIES_HOSPITALSTAFF"; }
        }

        protected override string GetHospitalStaffByUsernameDBPackageName
        {
            get { return "PCK_ENTITIES_HOSPITALSTAFF"; }
        }

        protected override string GetHospitalStaffByTypeDBPackageName
        {
            get { return "PCK_ENTITIES_HOSPITALSTAFF"; }
        }
    }
	 
}


