
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Glintths.Er.Workspaces.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AddMembersToWorkspaceRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "AddMembersToWorkspaceRequest", WrapperNamespace = "http://Glintths.Er.Services.Model/2011/Glintths")] 
	public partial class AddMembersToWorkspaceRequest
	{
		private string companyDB;
	 	private long workspaceId;
	 	private Glintths.Er.Common.DataContracts.WorkspaceMembers membersToAdd;
	 		
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "CompanyDB")]
		public string CompanyDB
		{
			get { return companyDB; }
			set { companyDB = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "WorkspaceId")]
		public long WorkspaceId
		{
			get { return workspaceId; }
			set { workspaceId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "MembersToAdd")]
		public Glintths.Er.Common.DataContracts.WorkspaceMembers MembersToAdd
		{
			get { return membersToAdd; }
			set { membersToAdd = value; }
		}
	}
}

