
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Glintths.Er.Workspaces.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CreateWorkspaceRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "CreateWorkspaceRequest", WrapperNamespace = "http://Glintths.Er.Services.Model/2011/Glintths")] 
	public partial class CreateWorkspaceRequest
	{
		private string companyDB;
	 	private string name;
	 	private string description;
	 	private Glintths.Er.Common.DataContracts.WorkspaceMember ownerUser;
	 	private System.Nullable<bool> active;
	 	private System.Nullable<long> parentId;
	 	private Glintths.Er.Common.DataContracts.WorkspaceMembers members;
	 	private System.Nullable<bool> inheritMembers;
	 		
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "CompanyDB")]
		public string CompanyDB
		{
			get { return companyDB; }
			set { companyDB = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "Name")]
		public string Name
		{
			get { return name; }
			set { name = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "Description")]
		public string Description
		{
			get { return description; }
			set { description = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "OwnerUser")]
		public Glintths.Er.Common.DataContracts.WorkspaceMember OwnerUser
		{
			get { return ownerUser; }
			set { ownerUser = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "Active")]
		public System.Nullable<bool> Active
		{
			get { return active; }
			set { active = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "ParentId")]
		public System.Nullable<long> ParentId
		{
			get { return parentId; }
			set { parentId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "Members")]
		public Glintths.Er.Common.DataContracts.WorkspaceMembers Members
		{
			get { return members; }
			set { members = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "InheritMembers")]
		public System.Nullable<bool> InheritMembers
		{
			get { return inheritMembers; }
			set { inheritMembers = value; }
		}
	}
}

