
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Glintths.Er.Workspaces.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CreateWorkspaceResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "CreateWorkspaceResponse", WrapperNamespace = "http://Glintths.Er.Services.Model/2011/Glintths")] 
	public partial class CreateWorkspaceResponse
	{
		private Glintths.Er.Common.DataContracts.Workspace workspace;
	 		
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "Workspace")]
		public Glintths.Er.Common.DataContracts.Workspace Workspace
		{
			get { return workspace; }
			set { workspace = value; }
		}
	}
}

