
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Glintths.Er.Workspaces.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetWorkspaceTreeResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetWorkspaceTreeResponse
	{
		private Glintths.Er.Common.DataContracts.Workspace rootWorkspace;
	 		
		[WCF::MessageBodyMember(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "RootWorkspace")]
		public Glintths.Er.Common.DataContracts.Workspace RootWorkspace
		{
			get { return rootWorkspace; }
			set { rootWorkspace = value; }
		}
	}
}

