using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 23 de Dezembro de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class AlertSubscription : AlertSubscription_GEN
	{
        public string Username { get; set; }
        public string CrudCode { get; set; }
        /// <summary>
        /// Initialize an new empty AlertSubscription object.
        /// </summary>
        public AlertSubscription() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty AlertSubscription object.
        /// </summary>
        public AlertSubscription(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  AlertSubscription object with the given parameters.
        /// </summary>
        public  AlertSubscription(long alertSubsUserId, long alertSubsInstId, long alertSubsPalceId, long alertSubsAppId, long alertSubsDocTypeId, long alertSubsAlertTypeId, string alertSubsParam, string alertSubsActive, string alertSubsNotify) : base(alertSubsUserId, alertSubsInstId, alertSubsPalceId, alertSubsAppId, alertSubsDocTypeId, alertSubsAlertTypeId, alertSubsParam, alertSubsActive, alertSubsNotify)
        {
        }
		
        public AlertSubscription(long alertSubsId) : base(alertSubsId)
        {
			
        }
	}
}


