using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Logging;

using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quarta-feira, 30 de Dezembro de 2009
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class DocumentIndexLog : DocumentIndexLog_GEN
	{
        /// <summary>
        /// Initialize an new empty DocumentIndexLog object.
        /// </summary>
        public DocumentIndexLog() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty DocumentIndexLog object.
        /// </summary>
        public DocumentIndexLog(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  DocumentIndexLog object with the given parameters.
        /// </summary>
        public  DocumentIndexLog(long docIdxLogDocLogId, string docIdxLogLevel, string docIdxLogMessage, string docIdxLogProcedure, string docIdxLogException, Nullable<DateTime> docIdxLogRegDate, string docIdxLogDetail) : base(docIdxLogDocLogId, docIdxLogLevel, docIdxLogMessage, docIdxLogProcedure, docIdxLogException, docIdxLogRegDate, docIdxLogDetail)
        {
        }
		
        public DocumentIndexLog(long docIdxLogId) : base(docIdxLogId)
        {
			
        }
	}
}


