
using System;
using System.Data;
using System.Collections;

using Cpchs.Eresults.Common.WCF.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
	
using CPCHS.Common.BusinessEntities;

using Microsoft.Practices.EnterpriseLibrary.Caching;

using Microsoft.Practices.EnterpriseLibrary.Logging;
using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;

namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: ter?a-feira, 20 de Outubro de 2009
    /// Created By: Generated by CodeSmith
		/// Template Created By: CPCHS psilva, 2005
    /// </summary>
	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public sealed class MonitoringManagementBER : MonitoringManagementBER_GEN
    {
		#region Singleton
		private static MonitoringManagementBER instance = new MonitoringManagementBER();
		
		public static MonitoringManagementBER Instance
		{
			get { return instance; }
		}
		#endregion
		private MonitoringManagementBER()
		{
			
		}

        protected override string GetDocLogsByMultiCriteriaDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string GetDocEpiLogsByMultiCriteriaDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string GetDocIdxLogsByMultiCriteriaDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string GetDocIdxLogsByLogIdMultiDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string  GetAlertsByMultiCriteriaDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string GetAlertsSubscriptionDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string InsertAlertSubscriptionDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string UpdateAlertSubscriptionDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string DeleteAlertSubscriptionDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string IgnoredAlertDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string CorrectedAlertDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override string ProcessIndexDocumentDBPackageName
        {
            get { return "PCK_DOCUMENTS_MONITORING"; }
        }

        protected override object[] InsertAlertSubscriptionDBParametersExtra(AlertSubscription obj)
        {
            return new object[] { obj.Username };
        }

        protected override object[]  UpdateAlertSubscriptionDBParametersExtra(AlertSubscription obj)
        {
            return new object[] { obj.Username };
        }
	}
}


