using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quinta-feira, 7 de Outubro de 2010
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class VideoLink : VideoLink_GEN
	{
        /// <summary>
        /// Initialize an new empty VideoLink object.
        /// </summary>
        public VideoLink() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty VideoLink object.
        /// </summary>
        public VideoLink(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  VideoLink object with the given parameters.
        /// </summary>
        public  VideoLink(long videoLinkElemId, long videoLinkVersionCode, long videoLinkId, string videoLinkUrl, long videoLinkHResolution, long videoLinkVResolution, long videoLinkSize, string videoLinkType) : base(videoLinkElemId, videoLinkVersionCode, videoLinkId, videoLinkUrl, videoLinkHResolution, videoLinkVResolution, videoLinkSize, videoLinkType)
        {
        }
		
        public VideoLink(long videoLinkElemId, long videoLinkVersionCode, long videoLinkId) : base(videoLinkElemId, videoLinkVersionCode, videoLinkId)
        {
			
        }
	}
}


