//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Glintths.Base.WCF.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - CodificationManagementSC
	/// </summary>
	[WCF::ServiceContract(Namespace = "urn:Glintths.Base", Name = "CodificationManagementSC", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface ICodificationManagementSC 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "urn:Glintths.Base.CodificationManagementSC.GetConfigurationByAreaKey", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Base.WCF.MessageContracts.GetConfigurationByAreaKeyResponse GetConfigurationByAreaKey(Glintths.Base.WCF.MessageContracts.GetConfigurationByAreaKeyRequest request);

[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "urn:Glintths.Base.CodificationManagementSC.GetConfigurationByScope", ReplyAction = "urn:Glintths.Base.CodificationManagementSC.GetConfigurationByScope", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Base.WCF.MessageContracts.GetConfigurationByScopeResponse GetConfigurationByScope(Glintths.Base.WCF.MessageContracts.GetConfigurationByScopeRequest request);

	}
}

