//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpchs.Documents.WCF.Proxy.LinksManagementSR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Links", Namespace="urn:Cpchs.Documents", ItemName="Link")]
    [System.SerializableAttribute()]
    public class Links : System.Collections.Generic.List<Cpchs.Documents.WCF.DataContracts.Link> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Cpchs.Documents", ConfigurationName="LinksManagementSR.LinksManagementSC")]
    public interface LinksManagementSC {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Cpchs.Documents.LinksManagementSC.GetDocumentLinks", ReplyAction="urn:Cpchs.Documents.LinksManagementSC.GetDocumentLinks")]
        Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetDocumentLinksResponse GetDocumentLinks(Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetDocumentLinksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Cpchs.Documents.LinksManagementSC.GetLinkByElementId", ReplyAction="urn:Cpchs.Documents.LinksManagementSC.GetLinkByElementId")]
        Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetLinkByElementIdResponse GetLinkByElementId(Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetLinkByElementIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentLinksRequest", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetDocumentLinksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public string CompanyDb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=1)]
        public long DocId;
        
        public GetDocumentLinksRequest() {
        }
        
        public GetDocumentLinksRequest(string CompanyDb, long DocId) {
            this.CompanyDb = CompanyDb;
            this.DocId = DocId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentLinksResponse", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetDocumentLinksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public Cpchs.Documents.WCF.DataContracts.LinkList DocumentLinks;
        
        public GetDocumentLinksResponse() {
        }
        
        public GetDocumentLinksResponse(Cpchs.Documents.WCF.DataContracts.LinkList DocumentLinks) {
            this.DocumentLinks = DocumentLinks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLinkByElementIdRequest", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetLinkByElementIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public string CompanyDb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=1)]
        public long ElementId;
        
        public GetLinkByElementIdRequest() {
        }
        
        public GetLinkByElementIdRequest(string CompanyDb, long ElementId) {
            this.CompanyDb = CompanyDb;
            this.ElementId = ElementId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLinkByElementIdResponse", WrapperNamespace="urn:Cpchs.Documents", IsWrapped=true)]
    public partial class GetLinkByElementIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Cpchs.Documents", Order=0)]
        public Cpchs.Documents.WCF.DataContracts.Link Link;
        
        public GetLinkByElementIdResponse() {
        }
        
        public GetLinkByElementIdResponse(Cpchs.Documents.WCF.DataContracts.Link Link) {
            this.Link = Link;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LinksManagementSCChannel : Cpchs.Documents.WCF.Proxy.LinksManagementSR.LinksManagementSC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinksManagementSCClient : System.ServiceModel.ClientBase<Cpchs.Documents.WCF.Proxy.LinksManagementSR.LinksManagementSC>, Cpchs.Documents.WCF.Proxy.LinksManagementSR.LinksManagementSC {
        
        public LinksManagementSCClient() {
        }
        
        public LinksManagementSCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinksManagementSCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinksManagementSCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinksManagementSCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetDocumentLinksResponse GetDocumentLinks(Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetDocumentLinksRequest request) {
            return base.Channel.GetDocumentLinks(request);
        }
        
        public Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetLinkByElementIdResponse GetLinkByElementId(Cpchs.Documents.WCF.Proxy.LinksManagementSR.GetLinkByElementIdRequest request) {
            return base.Channel.GetLinkByElementId(request);
        }
    }
}
