//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Glintths.Er.Workspaces.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - WorspacesManagementSC
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://Glintths.Er.Services.Model/2011/Glintths", Name = "WorspacesManagementSC", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IWorspacesManagementSC 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/CreateWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/CreateWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.CreateWorkspaceResponse CreateWorkspace(Glintths.Er.Workspaces.MessageContracts.CreateWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/ActivateWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/ActivateWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.ActivateWorkspaceResponse ActivateWorkspace(Glintths.Er.Workspaces.MessageContracts.ActivateWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/DeactivateWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/DeactivateWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.DeactivateWorkspaceResponse DeactivateWorkspace(Glintths.Er.Workspaces.MessageContracts.DeactivateWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/AddMembersToWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/AddMembersToWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.AddMembersToWorkspaceResponse AddMembersToWorkspace(Glintths.Er.Workspaces.MessageContracts.AddMembersToWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/RemoveMembersFromWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/RemoveMembersFromWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.RemoveMembersFromWorkspaceResponse RemoveMembersFromWorkspace(Glintths.Er.Workspaces.MessageContracts.RemoveMembersFromWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/GetWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/GetWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.GetWorkspaceResponse GetWorkspace(Glintths.Er.Workspaces.MessageContracts.GetWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/AddChildsToWorkspace", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/AddChildsToWorkspace", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.AddChildsToWorkspaceResponse AddChildsToWorkspace(Glintths.Er.Workspaces.MessageContracts.AddChildsToWorkspaceRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/GetWorkspaceTree", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/GetWorkspaceTree", ProtectionLevel = ProtectionLevel.None)]
		Glintths.Er.Workspaces.MessageContracts.GetWorkspaceTreeResponse GetWorkspaceTree(Glintths.Er.Workspaces.MessageContracts.GetWorkspaceTreeRequest request);

        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/RemoveWorkspaceDocument", ReplyAction = "http://Glintths.Er.Services.Model/2011/Glintths/WorspacesManagementSC/RemoveWorkspaceDocument", ProtectionLevel = ProtectionLevel.None)]
        Glintths.Er.Workspaces.MessageContracts.RemoveWorkspaceDocumentResponse RemoveWorkspaceDocument(Glintths.Er.Workspaces.MessageContracts.RemoveWorkspaceDocumentResquest request);
		
	
	}

}

