using System;
using System.Data;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using CPCHS.Common.BusinessEntities;
using Cpchs.Eresults.Common.WCF.BusinessEntities.Generated;
using System.Runtime.Serialization;
	
namespace Cpchs.Eresults.Common.WCF.BusinessEntities
{
    /// <summary>
    /// Date Created: quinta-feira, 5 de Julho de 2012
    /// Created By: Generated by CodeSmith
	/// Template Created By: CPCHS psilva, 2005
    /// </summary>
    [DataContract(Name = "Codif", Namespace = "http://glintt.com/types")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores"), Serializable]
    public class Codif : Codif_GEN
	{
        [DataMember]
        public string SubTitle { get; set; }
        /// <summary>
        /// Initialize an new empty Codif object.
        /// </summary>
        public Codif() : base()
        {
        }
		
		/// <summary>
        /// Initialize an new empty Codif object.
        /// </summary>
        public Codif(IDataReader reader, string companyDB) : base(reader, companyDB)
        {
        }
		
        /// <summary>
        /// Initialize a new  Codif object with the given parameters.
        /// </summary>
        public  Codif(string code, string descr) : base(code, descr)
        {
        }
		
		
		protected void LoadCodif(IDataReader reader, string companyDb)
        {
        }
	}
}


